// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: api-with-examples.yaml - Simple API overview, version 2.0.0 (OpenAPI 3.0)
//          https://github.com/OAI/learn.openapis.org/blob/main/examples/v3.0/api-with-examples.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'api_with_examples.NoArg'/>
        <see cref = 'api_with_examples.getVersionDetailsv2_200'/>
        <see cref = 'api_with_examples.getVersionDetailsv2_203'/>
        <see cref = 'api_with_examples.listVersionsv2_200'/>
        <see cref = 'api_with_examples.listVersionsv2_300'/>
    */
    [Title(@"Simple API overview")]
    [Version(@"2.0.0")]
    public interface api_with_examples {
        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        /// <summary>200 response</summary>
        public class listVersionsv2_200 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>300 response</summary>
        public class listVersionsv2_300 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>200 response</summary>
        public class getVersionDetailsv2_200 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>203 response</summary>
        public class getVersionDetailsv2_203 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            /// <summary>List API versions</summary>
            [HttpMethod(@"GET")]
            (L____________,
                /// <summary>200 response</summary>
                listVersionsv2_200,
                /// <summary>300 response</summary>
                listVersionsv2_300) listVersionsv2(NoArg _);

            public interface v2 {
                /// <summary>Show API version details</summary>
                [HttpMethod(@"GET")]
                (L____________,
                    /// <summary>200 response</summary>
                    getVersionDetailsv2_200,
                    /// <summary>203 response</summary>
                    getVersionDetailsv2_203) getVersionDetailsv2(NoArg _);
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        public class ContentTypeAttribute : Attribute { public ContentTypeAttribute(string MediaType = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }
    }
}
