// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: callback-example.yaml - Callback Example, version 1.0.0 (OpenAPI 3.0)
//          https://github.com/OAI/learn.openapis.org/blob/main/examples/v3.0/callback-example.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'callback_example.Code_202'/>
        <see cref = 'callback_example.Code_204'/>
        <see cref = 'callback_example.NoArg'/>
        <see cref = 'callback_example.post_streamsReq'/>
        <see cref = 'callback_example.post_streams_201'/>
        <see cref = 'callback_example.post_streams_onData_Req'/>
    */
    [Title(@"Callback Example")]
    [Version(@"1.0.0")]
    public interface callback_example {
        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        /// <summary>subscription payload</summary>
        public class post_streams_onData_Req {
            DateTime? timestamp;
            string? userData;
        }

        public class Code_202 { }

        public class Code_204 { }

        public class post_streamsReq {
            /// <summary>
            /// example: https://tonys-server.com
            /// the location where data will be sent.  Must be network accessible
            /// by the source server
            /// </summary>
            [Format(@"uri")]
            string callbackUrl; // in: query
        }

        /// <summary>subscription successfully created</summary>
        public class post_streams_201 {
            /// <summary>
            /// example: 2531329f-fb09-4ef7-887e-84e648214436
            ///
            /// this unique identifier allows management of the subscription
            /// </summary>
            string subscriptionId;
        }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            public interface streams {
                /// <summary>
                /// subscribes a client to receive out-of-band data
                /// callback onData: POST {$request.query.callbackUrl}/data
                /// </summary>
                [HttpMethod(@"POST")]
                public interface post : Actor {
                    int MaxActiveInstances => UNLIMITED;

                    [L____________<Return_post_streams, post_streamsReq>]
                    struct Call_post_streams { }

                    [____________R<CallbackState_post_streams, post_streams_201>]
                    struct Return_post_streams { }

                    [l____________<(Code_202, Code_204)>]
                    [____________r<post_streams_onData_Req>]
                    [L____________<End, NoArg>]
                    struct CallbackState_post_streams { }
                }
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        public class FormatAttribute : Attribute { public FormatAttribute(string Name = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }
    }
}
