// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: link-example.yaml - Link Example, version 1.0.0 (OpenAPI 3.0)
//          https://github.com/OAI/learn.openapis.org/blob/main/examples/v3.0/link-example.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'link_example.Code_204'/>
        <see cref = 'link_example.NoArg'/>
        <see cref = 'link_example.getPullRequestsByIdReq'/>
        <see cref = 'link_example.getPullRequestsByRepositoryReq'/>
        <see cref = 'link_example.getPullRequestsByRepository_200'/>
        <see cref = 'link_example.getRepositoriesByOwnerReq'/>
        <see cref = 'link_example.getRepositoriesByOwner_200'/>
        <see cref = 'link_example.getRepositoryReq'/>
        <see cref = 'link_example.getUserByNameReq'/>
        <see cref = 'link_example.mergePullRequestReq'/>
        <see cref = 'link_example.pullrequest'/>
        <see cref = 'link_example.repository'/>
        <see cref = 'link_example.user'/>
    */
    [Title(@"Link Example")]
    [Version(@"1.0.0")]
    public interface link_example {
        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        public class user {
            string? username;
            string? uuid;
        }

        public class repository {
            string? slug;
            user? owner;
        }

        public class pullrequest {
            int? id;
            string? title;
            repository? repository;
            user? author;
        }

        public class getUserByNameReq {
            string username; // in: path
        }

        public class getRepositoriesByOwnerReq {
            string username; // in: path
        }

        /// <summary>repositories owned by the supplied user</summary>
        public class getRepositoriesByOwner_200 {
            repository[,,] value;
        }

        public class getRepositoryReq {
            string username; // in: path
            string slug; // in: path
        }

        public class getPullRequestsByRepositoryReq {
            string username; // in: path
            string slug; // in: path
            getPullRequestsByRepositoryReq.State? state; // in: query

            public enum State {
                open,
                merged,
                declined,
            }
        }

        /// <summary>an array of pull request objects</summary>
        public class getPullRequestsByRepository_200 {
            pullrequest[,,] value;
        }

        public class getPullRequestsByIdReq {
            string username; // in: path
            string slug; // in: path
            string pid; // in: path
        }

        public class mergePullRequestReq {
            string username; // in: path
            string slug; // in: path
            string pid; // in: path
        }

        public class Code_204 { }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            // /2.0
            public interface N2ˍ0 {
                public interface users {
                    // /2.0/users/{username}
                    public interface username {
                        /// <summary>link userRepositories (after 200) → getRepositoriesByOwner: username = $response.body#/username</summary>
                        [HttpMethod(@"GET")]
                        public interface getUserByName : Actor {
                            int MaxActiveInstances => UNLIMITED;

                            [L____________<Return_getUserByName, getUserByNameReq>]
                            struct Call_getUserByName { }

                            [____________R<org.openapi.link_example.ClientServerConnection.N2ˍ0.repositories.username.getRepositoriesByOwner.Call_getRepositoriesByOwner, user>]
                            struct Return_getUserByName { }
                        }
                    }
                }

                public interface repositories {
                    // /2.0/repositories/{username}
                    public interface username {
                        /// <summary>
                        /// link userRepository (after 200) → getRepository: username = $response.body#/owner/username, slug =
                        /// $response.body#/slug
                        /// </summary>
                        [HttpMethod(@"GET")]
                        public interface getRepositoriesByOwner : Actor {
                            int MaxActiveInstances => UNLIMITED;

                            [L____________<Return_getRepositoriesByOwner, getRepositoriesByOwnerReq>]
                            struct Call_getRepositoriesByOwner { }

                            [____________R<org.openapi.link_example.ClientServerConnection.N2ˍ0.repositories.username.slug.getRepository.Call_getRepository, getRepositoriesByOwner_200>]
                            struct Return_getRepositoriesByOwner { }
                        }

                        // /2.0/repositories/{username}/{slug}
                        public interface slug {
                            /// <summary>
                            /// link repositoryPullRequests (after 200) → getPullRequestsByRepository: username =
                            /// $response.body#/owner/username, slug = $response.body#/slug
                            /// </summary>
                            [HttpMethod(@"GET")]
                            public interface getRepository : Actor {
                                int MaxActiveInstances => UNLIMITED;

                                [L____________<Return_getRepository, getRepositoryReq>]
                                struct Call_getRepository { }

                                [____________R<org.openapi.link_example.ClientServerConnection.N2ˍ0.repositories.username.slug.pullrequests.getPullRequestsByRepository.Call_getPullRequestsByRepository, repository>]
                                struct Return_getRepository { }
                            }

                            public interface pullrequests {
                                [HttpMethod(@"GET")]
                                public interface getPullRequestsByRepository : Actor {
                                    int MaxActiveInstances => UNLIMITED;

                                    [L____________<Return_getPullRequestsByRepository, getPullRequestsByRepositoryReq>]
                                    struct Call_getPullRequestsByRepository { }

                                    [____________R<End, getPullRequestsByRepository_200>]
                                    struct Return_getPullRequestsByRepository { }
                                }

                                // /2.0/repositories/{username}/{slug}/pullrequests/{pid}
                                public interface pid {
                                    /// <summary>
                                    /// link pullRequestMerge (after 200) → mergePullRequest: username = $response.body#/author/username, slug =
                                    /// $response.body#/repository/slug, pid = $response.body#/id
                                    /// </summary>
                                    [HttpMethod(@"GET")]
                                    public interface getPullRequestsById : Actor {
                                        int MaxActiveInstances => UNLIMITED;

                                        [L____________<Return_getPullRequestsById, getPullRequestsByIdReq>]
                                        struct Call_getPullRequestsById { }

                                        [____________R<org.openapi.link_example.ClientServerConnection.N2ˍ0.repositories.username.slug.pullrequests.pid.merge.mergePullRequest.Call_mergePullRequest, pullrequest>]
                                        struct Return_getPullRequestsById { }
                                    }

                                    public interface merge {
                                        [HttpMethod(@"POST")]
                                        public interface mergePullRequest : Actor {
                                            int MaxActiveInstances => UNLIMITED;

                                            [L____________<Return_mergePullRequest, mergePullRequestReq>]
                                            struct Call_mergePullRequest { }

                                            [____________R<End, Code_204>]
                                            struct Return_mergePullRequest { }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }
    }
}
