// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: non-oauth-scopes.yaml - Non-oAuth Scopes example, version 1.0.0 (OpenAPI 3.1)
//          https://github.com/OAI/learn.openapis.org/blob/main/examples/v3.1/non-oauth-scopes.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'non_oauth_scopes.NoArg'/>
    */
    [Title(@"Non-oAuth Scopes example")]
    [Version(@"1.0.0")]
    public interface non_oauth_scopes {
        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        /// <summary>note: non-oauth scopes are not defined at the securityScheme level</summary>
        [BearerAuth(@"jwt")]
        public class bearerAuth { }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            public interface users {
                /// <summary>security: bearerAuth</summary>
                [HttpMethod(@"GET")]
                [SecurityRequirement(@"bearerAuth", @"read:users,public")]
                (L____________, NoArg) get(NoArg _);
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class BearerAuthAttribute : Attribute { public BearerAuthAttribute(string BearerFormat = "") { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class SecurityRequirementAttribute : Attribute { public SecurityRequirementAttribute(string Scheme = "", string Scopes = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }
    }
}
