// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: petstore.yaml - Swagger Petstore, version 1.0.0 (OpenAPI 3.0)
//          https://github.com/OAI/learn.openapis.org/blob/main/examples/v3.0/petstore.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'petstore.Code_201'/> pets
        <see cref = 'petstore.Error'/> pets
        <see cref = 'petstore.NoArg'/>
        <see cref = 'petstore.Pet'/> pets
        <see cref = 'petstore.listPetsReq'/> pets
        <see cref = 'petstore.listPets_200'/> pets
        <see cref = 'petstore.showPetByIdReq'/> pets
    */
    [Title(@"Swagger Petstore")]
    [Version(@"1.0.0")]
    [License(@"MIT", @"", @"")]
    public interface petstore {
        // 64-bit integers are `long` / `ulong` here, as `format: int64` says. A JSON number goes through a
        // double in JavaScript, so values above 2^53 never arrived there intact: if TypeScript hosts
        // matter and the values stay below that, `longJS` / `ulongJS` are the cheaper types.
        //
        // The document states ranges, never distributions. Where the values of an integer cluster - a
        // counter near its floor, a budget near its ceiling, a delta around zero - [A], [V] or [X] on
        // that field is the most valuable edit after conversion.

        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        /// <summary>Shared error pack set - error schemas reused across operations.</summary>
        public interface StandardErrors : _<Error> { }

        // ═════════════════════════ packs ═════════════════════════

        public class Pet {
            long id;
            string name;
            string? tag;
        }

        public class Pets {
            [D(100)]
            Pet[,,] TYPEDEF;
        }

        public class Error {
            int code;
            string message;
        }

        public class listPetsReq {
            /// <summary>How many items to return at one time (max 100)</summary>
            [V(100)]
            int? limit; // in: query
        }

        /// <summary>A paged array of pets</summary>
        public class listPets_200 {
            Pets value;
        }

        public class Code_201 { }

        public class showPetByIdReq {
            /// <summary>The id of the pet to retrieve</summary>
            string petId; // in: path
        }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// http://petstore.swagger.io/v1
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        [Server(@"http://petstore.swagger.io/v1", @"", @"")]
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            public interface pets {
                /// <summary>
                /// List all pets
                /// tags: pets
                /// HTTP header on 200: x-next (String) - A link to the next page of responses
                /// </summary>
                [HttpMethod(@"GET")]
                [Tag(@"pets", @"")]
                (L____________,
                    /// <summary>A paged array of pets</summary>
                    listPets_200,
                    /// <summary>shared errors</summary>
                    StandardErrors) listPets(listPetsReq req);

                /// <summary>
                /// Create a pet
                /// tags: pets
                /// </summary>
                [HttpMethod(@"POST")]
                [Tag(@"pets", @"")]
                (L____________,
                    /// <summary>Null response</summary>
                    Code_201,
                    /// <summary>shared errors</summary>
                    StandardErrors) createPets(Pet req);

                // /pets/{petId}
                public interface petId {
                    /// <summary>
                    /// Info for a specific pet
                    /// tags: pets
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"pets", @"")]
                    (L____________,
                        /// <summary>Expected response to a valid request</summary>
                        Pet,
                        /// <summary>shared errors</summary>
                        StandardErrors) showPetById(showPetByIdReq req);
                }
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ServerAttribute : Attribute { public ServerAttribute(string Url = "", string Description = "", string Name = "") { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagAttribute : Attribute { public TagAttribute(string Name = "", string Description = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }

        public class LicenseAttribute : Attribute { public LicenseAttribute(string Name = "", string Identifier = "", string Url = "") { } }
    }
}
