// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: petstore-expanded.yaml - Swagger Petstore, version 1.0.0 (OpenAPI 3.0)
//          https://github.com/OAI/learn.openapis.org/blob/main/examples/v3.0/petstore-expanded.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'petstore_expanded.Code_204'/>
        <see cref = 'petstore_expanded.Error'/>
        <see cref = 'petstore_expanded.NewPet'/>
        <see cref = 'petstore_expanded.NoArg'/>
        <see cref = 'petstore_expanded.Pet'/>
        <see cref = 'petstore_expanded.deletePetReq'/>
        <see cref = 'petstore_expanded.findPetsReq'/>
        <see cref = 'petstore_expanded.findPets_200'/>
        <see cref = 'petstore_expanded.find_pet_by_idReq'/>
    */
    [Title(@"Swagger Petstore")]
    [Version(@"1.0.0")]
    [Description(@"A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification")]
    [Contact(@"Swagger API Team", @"apiteam@swagger.io", @"http://swagger.io/")]
    [License(@"Apache 2.0", @"", @"https://www.apache.org/licenses/LICENSE-2.0.html")]
    [TermsOfService(@"http://swagger.io/terms/")]
    public interface petstore_expanded {
        // 64-bit integers are `long` / `ulong` here, as `format: int64` says. A JSON number goes through a
        // double in JavaScript, so values above 2^53 never arrived there intact: if TypeScript hosts
        // matter and the values stay below that, `longJS` / `ulongJS` are the cheaper types.
        //
        // The document states ranges, never distributions. Where the values of an integer cluster - a
        // counter near its floor, a budget near its ceiling, a delta around zero - [A], [V] or [X] on
        // that field is the most valuable edit after conversion.

        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        /// <summary>Shared error pack set - error schemas reused across operations.</summary>
        public interface StandardErrors : _<Error> { }

        // ═════════════════════════ packs ═════════════════════════

        public class Pet : NewPet {
            long id;
        }

        public class NewPet {
            string name;
            string? tag;
        }

        public class Error {
            int code;
            string message;
        }

        public class findPetsReq {
            /// <summary>tags to filter by</summary>
            string[,,]? tags; // in: query

            /// <summary>maximum number of results to return</summary>
            int? limit; // in: query
        }

        /// <summary>pet response</summary>
        public class findPets_200 {
            Pet[,,] value;
        }

        public class find_pet_by_idReq {
            /// <summary>ID of pet to fetch</summary>
            long id; // in: path
        }

        public class deletePetReq {
            /// <summary>ID of pet to delete</summary>
            long id; // in: path
        }

        public class Code_204 { }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// https://petstore.swagger.io/v2
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        [Server(@"https://petstore.swagger.io/v2", @"", @"")]
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            public interface pets {
                /// <summary>
                /// Returns all pets from the system that the user has access to
                /// Nam sed condimentum est. Maecenas tempor sagittis sapien, nec rhoncus sem sagittis sit amet. Aenean at gravida
                /// augue, ac iaculis sem. Curabitur odio lorem, ornare eget elementum nec, cursus id lectus. Duis mi turpis,
                /// pulvinar ac eros ac, tincidunt varius justo. In hac habitasse platea dictumst. Integer at adipiscing ante, a
                /// sagittis ligula. Aenean pharetra tempor ante molestie imperdiet. Vivamus id aliquam diam. Cras quis velit non
                /// tortor eleifend sagittis. Praesent at enim pharetra urna volutpat venenatis eget eget mauris. In eleifend
                /// fermentum facilisis. Praesent enim enim, gravida ac sodales sed, placerat id erat. Suspendisse lacus dolor,
                /// consectetur non augue vel, vehicula interdum libero. Morbi euismod sagittis libero sed lacinia.
                ///
                /// Sed tempus felis lobortis leo pulvinar rutrum. Nam mattis velit nisl, eu condimentum ligula luctus nec.
                /// Phasellus semper velit eget aliquet faucibus. In a mattis elit. Phasellus vel urna viverra, condimentum lorem
                /// id, rhoncus nibh. Ut pellentesque posuere elementum. Sed a varius odio. Morbi rhoncus ligula libero, vel
                /// eleifend nunc tristique vitae. Fusce et sem dui. Aenean nec scelerisque tortor. Fusce malesuada accumsan magna
                /// vel tempus. Quisque mollis felis eu dolor tristique, sit amet auctor felis gravida. Sed libero lorem, molestie
                /// sed nisl in, accumsan tempor nisi. Fusce sollicitudin massa ut lacinia mattis. Sed vel eleifend lorem.
                /// Pellentesque vitae felis pretium, pulvinar elit eu, euismod sapien.
                /// </summary>
                [HttpMethod(@"GET")]
                (L____________,
                    /// <summary>pet response</summary>
                    findPets_200,
                    /// <summary>shared errors</summary>
                    StandardErrors) findPets(findPetsReq req);

                /// <summary>Creates a new pet in the store. Duplicates are allowed</summary>
                [HttpMethod(@"POST")]
                (L____________,
                    /// <summary>pet response</summary>
                    Pet,
                    /// <summary>shared errors</summary>
                    StandardErrors) addPet(NewPet req);

                // /pets/{id}
                public interface id {
                    /// <summary>
                    /// Returns a user based on a single ID, if the user does not have access to the pet
                    /// operationId: find pet by id
                    /// </summary>
                    [HttpMethod(@"GET")]
                    (L____________,
                        /// <summary>pet response</summary>
                        Pet,
                        /// <summary>shared errors</summary>
                        StandardErrors) find_pet_by_id(find_pet_by_idReq req);

                    /// <summary>deletes a single pet based on the ID supplied</summary>
                    [HttpMethod(@"DELETE")]
                    (L____________,
                        /// <summary>pet deleted</summary>
                        Code_204,
                        /// <summary>shared errors</summary>
                        StandardErrors) deletePet(deletePetReq req);
                }
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ServerAttribute : Attribute { public ServerAttribute(string Url = "", string Description = "", string Name = "") { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }

        public class DescriptionAttribute : Attribute { public DescriptionAttribute(string Description = "") { } }

        public class ContactAttribute : Attribute { public ContactAttribute(string Name = "", string Email = "", string Url = "") { } }

        public class LicenseAttribute : Attribute { public LicenseAttribute(string Name = "", string Identifier = "", string Url = "") { } }

        public class TermsOfServiceAttribute : Attribute { public TermsOfServiceAttribute(string Url = "") { } }
    }
}
