// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: swagger-petstore-v3.yaml - Swagger Petstore - OpenAPI 3.0, version 1.0.29-SNAPSHOT (OpenAPI 3.0)
//          https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'swagger_petstore_v3.ApiResponse'/> pet
        <see cref = 'swagger_petstore_v3.Category'/>
        <see cref = 'swagger_petstore_v3.Code_200'/> pet | store | user
        <see cref = 'swagger_petstore_v3.Code_400'/> pet | store | user
        <see cref = 'swagger_petstore_v3.Code_404'/> pet | store | user
        <see cref = 'swagger_petstore_v3.Code_422'/> pet | store
        <see cref = 'swagger_petstore_v3.Code_default'/> pet | store | user
        <see cref = 'swagger_petstore_v3.NoArg'/>
        <see cref = 'swagger_petstore_v3.Order'/> store
        <see cref = 'swagger_petstore_v3.Pet'/> pet
        <see cref = 'swagger_petstore_v3.Pet_Body'/>
        <see cref = 'swagger_petstore_v3.Tag'/>
        <see cref = 'swagger_petstore_v3.User'/> user
        <see cref = 'swagger_petstore_v3.UserArray'/>
        <see cref = 'swagger_petstore_v3.createUsersWithListInputReq'/> user
        <see cref = 'swagger_petstore_v3.deleteOrderReq'/> store
        <see cref = 'swagger_petstore_v3.deletePetReq'/> pet
        <see cref = 'swagger_petstore_v3.deleteUserReq'/> user
        <see cref = 'swagger_petstore_v3.findPetsByStatusReq'/> pet
        <see cref = 'swagger_petstore_v3.findPetsByStatus_200'/> pet
        <see cref = 'swagger_petstore_v3.findPetsByTagsReq'/> pet
        <see cref = 'swagger_petstore_v3.findPetsByTags_200'/> pet
        <see cref = 'swagger_petstore_v3.getInventory_200'/> store
        <see cref = 'swagger_petstore_v3.getOrderByIdReq'/> store
        <see cref = 'swagger_petstore_v3.getPetByIdReq'/> pet
        <see cref = 'swagger_petstore_v3.getUserByNameReq'/> user
        <see cref = 'swagger_petstore_v3.loginUserReq'/> user
        <see cref = 'swagger_petstore_v3.loginUser_200'/> user
        <see cref = 'swagger_petstore_v3.updatePetWithFormReq'/> pet
        <see cref = 'swagger_petstore_v3.updateUserReq'/> user
        <see cref = 'swagger_petstore_v3.uploadFileReq'/> pet
    */
    [Title(@"Swagger Petstore - OpenAPI 3.0")]
    [Version(@"1.0.29-SNAPSHOT")]
    [Description(@"This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)")]
    [Contact(@"", @"apiteam@swagger.io", @"")]
    [License(@"Apache 2.0", @"", @"https://www.apache.org/licenses/LICENSE-2.0.html")]
    [ExternalDocs(@"Find out more about Swagger", @"https://swagger.io/")]
    [TermsOfService(@"https://swagger.io/terms/")]
    [TagDefinition(@"pet", @"Everything about your Pets", @"", @"", @"")]
    [TagExternalDocs(@"pet", @"Find out more", @"https://swagger.io/")]
    [TagDefinition(@"store", @"Access to Petstore orders", @"", @"", @"")]
    [TagExternalDocs(@"store", @"Find out more about our store", @"https://swagger.io/")]
    [TagDefinition(@"user", @"Operations about user", @"", @"", @"")]
    public interface swagger_petstore_v3 {
        // 64-bit integers are `long` / `ulong` here, as `format: int64` says. A JSON number goes through a
        // double in JavaScript, so values above 2^53 never arrived there intact: if TypeScript hosts
        // matter and the values stay below that, `longJS` / `ulongJS` are the cheaper types.
        //
        // The document states ranges, never distributions. Where the values of an integer cluster - a
        // counter near its floor, a budget near its ceiling, a delta around zero - [A], [V] or [X] on
        // that field is the most valuable edit after conversion.

        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        /// <summary>Shared error pack set - error schemas reused across operations.</summary>
        public interface StandardErrors : _<(Code_400, Code_404, Code_422, Code_default)> { }

        // ═════════════════════════ packs ═════════════════════════

        [OAuth2AuthImplicit(@"https://petstore3.swagger.io/oauth/authorize", @"")]
        public class petstore_auth {
            public enum petstore_authScope {
                /// <summary>modify pets in your account</summary>
                write_pets,
                /// <summary>read your pets</summary>
                read_pets,
            }
        }

        [ApiKeyAuth(@"api_key", @"Header")]
        public class api_key { }

        [Extension(@"x-swagger-router-model", @"io.swagger.petstore.model.Order")]
        public class Order {
            /// <summary>example: 10</summary>
            long? id;

            /// <summary>example: 198772</summary>
            long? petId;

            /// <summary>example: 7</summary>
            int? quantity;
            DateTime? shipDate;

            /// <summary>
            /// example: approved
            ///
            /// Order Status
            /// </summary>
            Order.Status? status;
            bool? complete;

            public enum Status {
                placed,
                approved,
                delivered,
            }
        }

        [Extension(@"x-swagger-router-model", @"io.swagger.petstore.model.Category")]
        public class Category {
            /// <summary>example: 1</summary>
            long? id;

            /// <summary>example: Dogs</summary>
            string? name;
        }

        [Extension(@"x-swagger-router-model", @"io.swagger.petstore.model.User")]
        public class User {
            /// <summary>example: 10</summary>
            long? id;

            /// <summary>example: theUser</summary>
            string? username;

            /// <summary>example: John</summary>
            string? firstName;

            /// <summary>example: James</summary>
            string? lastName;

            /// <summary>example: john@email.com</summary>
            string? email;

            /// <summary>example: 12345</summary>
            string? password;

            /// <summary>example: 12345</summary>
            string? phone;

            /// <summary>
            /// example: 1
            ///
            /// User Status
            /// </summary>
            int? userStatus;
        }

        [Extension(@"x-swagger-router-model", @"io.swagger.petstore.model.Tag")]
        public class Tag {
            long? id;
            string? name;
        }

        [Extension(@"x-swagger-router-model", @"io.swagger.petstore.model.Pet")]
        public class Pet {
            /// <summary>example: 10</summary>
            long? id;

            /// <summary>example: doggie</summary>
            string name;
            Category? category;
            string[,,] photoUrls;
            Tag[,,]? tags;

            /// <summary>pet status in the store</summary>
            Pet.Status? status;

            public enum Status {
                available,
                pending,
                sold,
            }
        }

        public class ApiResponse {
            int? code;
            string? Type;
            string? message;
        }

        /// <summary>Pet object that needs to be added to the store</summary>
        public class Pet_Body : Pet { }

        /// <summary>List of user object</summary>
        public class UserArray {
            User[,,] body;
        }

        public class Code_400 { }

        public class Code_404 { }

        public class Code_422 { }

        public class Code_default { }

        public class findPetsByStatusReq {
            /// <summary>Status values that need to be considered for filter</summary>
            [Default(@"available")]
            Pet.Status status; // in: query
        }

        /// <summary>successful operation</summary>
        public class findPetsByStatus_200 {
            Pet[,,] value;
        }

        public class findPetsByTagsReq {
            /// <summary>Tags to filter by</summary>
            string[,,] tags; // in: query
        }

        /// <summary>successful operation</summary>
        public class findPetsByTags_200 {
            Pet[,,] value;
        }

        public class getPetByIdReq {
            /// <summary>ID of pet to return</summary>
            long petId; // in: path
        }

        public class updatePetWithFormReq {
            /// <summary>ID of pet that needs to be updated</summary>
            long petId; // in: path

            /// <summary>Name of pet that needs to be updated</summary>
            string? name; // in: query

            /// <summary>Status of pet that needs to be updated</summary>
            string? status; // in: query
        }

        public class deletePetReq {
            string? api_key; // in: header

            /// <summary>Pet id to delete</summary>
            long petId; // in: path
        }

        public class Code_200 { }

        public class uploadFileReq {
            [ContentType(@"application/octet-stream")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File body;

            /// <summary>ID of pet to update</summary>
            long petId; // in: path

            /// <summary>Additional Metadata</summary>
            string? additionalMetadata; // in: query
        }

        /// <summary>successful operation</summary>
        public class getInventory_200 {
            Map<string, int> value;
        }

        public class getOrderByIdReq {
            /// <summary>ID of order that needs to be fetched</summary>
            long orderId; // in: path
        }

        public class deleteOrderReq {
            /// <summary>ID of the order that needs to be deleted</summary>
            long orderId; // in: path
        }

        public class createUsersWithListInputReq {
            User[,,] body;
        }

        public class loginUserReq {
            /// <summary>The user name for login</summary>
            string? username; // in: query

            /// <summary>The password for login in clear text</summary>
            string? password; // in: query
        }

        /// <summary>successful operation</summary>
        public class loginUser_200 {
            string value;
        }

        /// <summary>HTTP response header `X-Rate-Limit`, parsed before the payload.</summary>
        public class X_Rate_Limit_int : HeaderFor<loginUser_200> {
            /// <summary>calls per hour allowed by the user</summary>
            int X_Rate_Limit;
        }

        public class getUserByNameReq {
            /// <summary>The name that needs to be fetched. Use user1 for testing</summary>
            string username; // in: path
        }

        /// <summary>Update an existent user in the store</summary>
        public class updateUserReq : User {
            /// <summary>name that need to be deleted</summary>
            string Username; // in: path
        }

        public class deleteUserReq {
            /// <summary>The name that needs to be deleted</summary>
            string username; // in: path
        }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// https://petstore3.swagger.io/api/v3
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        [Server(@"https://petstore3.swagger.io/api/v3", @"", @"")]
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            public interface pet {
                /// <summary>
                /// Update an existing pet.
                /// Update an existing pet by Id.
                /// tags: pet
                /// security: petstore_auth
                /// </summary>
                [HttpMethod(@"PUT")]
                [Tag(@"pet", @"Everything about your Pets")]
                [TagExternalDocs(@"pet", @"Find out more", @"https://swagger.io/")]
                [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                (L____________,
                    /// <summary>Successful operation</summary>
                    Pet,
                    /// <summary>shared errors</summary>
                    StandardErrors) updatePet(Pet req);

                /// <summary>
                /// Add a new pet to the store.
                /// tags: pet
                /// security: petstore_auth
                /// </summary>
                [HttpMethod(@"POST")]
                [Tag(@"pet", @"Everything about your Pets")]
                [TagExternalDocs(@"pet", @"Find out more", @"https://swagger.io/")]
                [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                (L____________,
                    /// <summary>Successful operation</summary>
                    Pet,
                    /// <summary>shared errors</summary>
                    StandardErrors) addPet(Pet req);

                public interface findByStatus {
                    /// <summary>
                    /// Finds Pets by status.
                    /// Multiple status values can be provided with comma separated strings.
                    /// tags: pet
                    /// security: petstore_auth
                    /// The reply 200 is also offered as application/xml: one form is carried.
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"https://swagger.io/")]
                    [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        findPetsByStatus_200,
                        /// <summary>shared errors</summary>
                        StandardErrors) findPetsByStatus(findPetsByStatusReq req);
                }

                public interface findByTags {
                    /// <summary>
                    /// Finds Pets by tags.
                    /// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
                    /// tags: pet
                    /// security: petstore_auth
                    /// The reply 200 is also offered as application/xml: one form is carried.
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"https://swagger.io/")]
                    [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        findPetsByTags_200,
                        /// <summary>shared errors</summary>
                        StandardErrors) findPetsByTags(findPetsByTagsReq req);
                }

                // /pet/{petId}
                public interface petId {
                    /// <summary>
                    /// Find pet by ID.
                    /// Returns a single pet.
                    /// tags: pet
                    /// security: api_key, petstore_auth
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"https://swagger.io/")]
                    [SecurityRequirement(@"api_key", @"")]
                    [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        Pet,
                        /// <summary>shared errors</summary>
                        StandardErrors) getPetById(getPetByIdReq req);

                    /// <summary>
                    /// Updates a pet in the store with form data.
                    /// Updates a pet resource based on the form data.
                    /// tags: pet
                    /// security: petstore_auth
                    /// </summary>
                    [HttpMethod(@"POST")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"https://swagger.io/")]
                    [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        Pet,
                        /// <summary>shared errors</summary>
                        StandardErrors) updatePetWithForm(updatePetWithFormReq req);

                    /// <summary>
                    /// Deletes a pet.
                    /// Delete a pet.
                    /// tags: pet
                    /// security: petstore_auth
                    /// </summary>
                    [HttpMethod(@"DELETE")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"https://swagger.io/")]
                    [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                    (L____________,
                        /// <summary>Pet deleted</summary>
                        Code_200,
                        /// <summary>shared errors</summary>
                        StandardErrors) deletePet(deletePetReq req);

                    public interface uploadImage {
                        /// <summary>
                        /// Uploads an image.
                        /// Upload image of the pet.
                        /// tags: pet
                        /// security: petstore_auth
                        /// </summary>
                        [HttpMethod(@"POST")]
                        [Tag(@"pet", @"Everything about your Pets")]
                        [TagExternalDocs(@"pet", @"Find out more", @"https://swagger.io/")]
                        [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                        (L____________,
                            /// <summary>successful operation</summary>
                            ApiResponse,
                            /// <summary>shared errors</summary>
                            StandardErrors) uploadFile(uploadFileReq req);
                    }
                }
            }

            public interface store {
                public interface inventory {
                    /// <summary>
                    /// Returns pet inventories by status.
                    /// Returns a map of status codes to quantities.
                    /// tags: store
                    /// security: api_key
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"store", @"Access to Petstore orders")]
                    [TagExternalDocs(@"store", @"Find out more about our store", @"https://swagger.io/")]
                    [SecurityRequirement(@"api_key", @"")]
                    [Extension(@"x-swagger-router-controller", @"OrderController")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        getInventory_200,
                        /// <summary>shared errors</summary>
                        StandardErrors) getInventory(NoArg _);
                }

                public interface order {
                    /// <summary>
                    /// Place an order for a pet.
                    /// Place a new order in the store.
                    /// tags: store
                    /// </summary>
                    [HttpMethod(@"POST")]
                    [Tag(@"store", @"Access to Petstore orders")]
                    [TagExternalDocs(@"store", @"Find out more about our store", @"https://swagger.io/")]
                    [Extension(@"x-swagger-router-controller", @"OrderController")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        Order,
                        /// <summary>shared errors</summary>
                        StandardErrors) placeOrder(Order req);

                    // /store/order/{orderId}
                    public interface orderId {
                        /// <summary>
                        /// Find purchase order by ID.
                        /// For valid response try integer IDs with value &lt;= 5 or > 10. Other values will generate exceptions.
                        /// tags: store
                        /// </summary>
                        [HttpMethod(@"GET")]
                        [Tag(@"store", @"Access to Petstore orders")]
                        [TagExternalDocs(@"store", @"Find out more about our store", @"https://swagger.io/")]
                        [Extension(@"x-swagger-router-controller", @"OrderController")]
                        (L____________,
                            /// <summary>successful operation</summary>
                            Order,
                            /// <summary>shared errors</summary>
                            StandardErrors) getOrderById(getOrderByIdReq req);

                        /// <summary>
                        /// Delete purchase order by identifier.
                        /// For valid response try integer IDs with value &lt; 1000. Anything above 1000 or non-integers will generate API
                        /// errors.
                        /// tags: store
                        /// </summary>
                        [HttpMethod(@"DELETE")]
                        [Tag(@"store", @"Access to Petstore orders")]
                        [TagExternalDocs(@"store", @"Find out more about our store", @"https://swagger.io/")]
                        [Extension(@"x-swagger-router-controller", @"OrderController")]
                        (L____________,
                            /// <summary>order deleted</summary>
                            Code_200,
                            /// <summary>shared errors</summary>
                            StandardErrors) deleteOrder(deleteOrderReq req);
                    }
                }
            }

            public interface user {
                /// <summary>
                /// Create user.
                /// This can only be done by the logged in user.
                /// tags: user
                /// </summary>
                [HttpMethod(@"POST")]
                [Tag(@"user", @"Operations about user")]
                [Extension(@"x-swagger-router-controller", @"UserController")]
                (L____________,
                    /// <summary>successful operation</summary>
                    User,
                    /// <summary>shared errors</summary>
                    StandardErrors) createUser(User req);

                public interface createWithList {
                    /// <summary>
                    /// Creates list of users with given input array.
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"POST")]
                    [Tag(@"user", @"Operations about user")]
                    [Extension(@"x-swagger-router-controller", @"UserController")]
                    (L____________,
                        /// <summary>Successful operation</summary>
                        User,
                        /// <summary>shared errors</summary>
                        StandardErrors) createUsersWithListInput(createUsersWithListInputReq req);
                }

                public interface login {
                    /// <summary>
                    /// Logs user into the system.
                    /// Log into the system.
                    /// tags: user
                    /// The reply 200 is also offered as application/xml: one form is carried.
                    /// HTTP header on 200: X-Expires-After (String) - date in UTC when token expires
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"user", @"Operations about user")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        loginUser_200,
                        /// <summary>shared errors</summary>
                        StandardErrors) loginUser(loginUserReq req);
                }

                public interface logout {
                    /// <summary>
                    /// Logs out current logged in user session.
                    /// Log user out of the system.
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"user", @"Operations about user")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        Code_200,
                        /// <summary>shared errors</summary>
                        StandardErrors) logoutUser(NoArg _);
                }

                // /user/{username}
                public interface username {
                    /// <summary>
                    /// Get user by user name.
                    /// Get user detail based on username.
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"user", @"Operations about user")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        User,
                        /// <summary>shared errors</summary>
                        StandardErrors) getUserByName(getUserByNameReq req);

                    /// <summary>
                    /// Update user resource.
                    /// This can only be done by the logged in user.
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"PUT")]
                    [Tag(@"user", @"Operations about user")]
                    [Extension(@"x-swagger-router-controller", @"UserController")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        Code_200,
                        /// <summary>shared errors</summary>
                        StandardErrors) updateUser(updateUserReq req);

                    /// <summary>
                    /// Delete user resource.
                    /// This can only be done by the logged in user.
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"DELETE")]
                    [Tag(@"user", @"Operations about user")]
                    (L____________,
                        /// <summary>User deleted</summary>
                        Code_200,
                        /// <summary>shared errors</summary>
                        StandardErrors) deleteUser(deleteUserReq req);
                }
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class OAuth2AuthImplicitAttribute : Attribute { public OAuth2AuthImplicitAttribute(string AuthorizationUrl = "", string RefreshUrl = "") { } }

        public class ApiKeyAuthAttribute : Attribute { public ApiKeyAuthAttribute(string Name = "", string In = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ServerAttribute : Attribute { public ServerAttribute(string Url = "", string Description = "", string Name = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ExtensionAttribute : Attribute { public ExtensionAttribute(string Key = "", string Value = "") { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagAttribute : Attribute { public TagAttribute(string Name = "", string Description = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagExternalDocsAttribute : Attribute { public TagExternalDocsAttribute(string TagName = "", string Description = "", string Url = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class SecurityRequirementAttribute : Attribute { public SecurityRequirementAttribute(string Scheme = "", string Scopes = "") { } }

        public class DefaultAttribute : Attribute { public DefaultAttribute(double value) { } public DefaultAttribute(long value) { } public DefaultAttribute(string value) { } public DefaultAttribute(bool value) { } }

        public class ContentTypeAttribute : Attribute { public ContentTypeAttribute(string MediaType = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagDefinitionAttribute : Attribute { public TagDefinitionAttribute(string Name = "", string Description = "", string Summary = "", string Parent = "", string Kind = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }

        public class DescriptionAttribute : Attribute { public DescriptionAttribute(string Description = "") { } }

        public class ContactAttribute : Attribute { public ContactAttribute(string Name = "", string Email = "", string Url = "") { } }

        public class LicenseAttribute : Attribute { public LicenseAttribute(string Name = "", string Identifier = "", string Url = "") { } }

        public class ExternalDocsAttribute : Attribute { public ExternalDocsAttribute(string Description = "", string Url = "") { } }

        public class TermsOfServiceAttribute : Attribute { public TermsOfServiceAttribute(string Url = "") { } }
    }
}
