// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: swagger-petstore-v2.json - Swagger Petstore, version 1.0.7 (Swagger 2.0)
//          https://petstore.swagger.io/v2/swagger.json
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'swagger_petstore_v2.ApiResponse'/> pet
        <see cref = 'swagger_petstore_v2.Category'/>
        <see cref = 'swagger_petstore_v2.NoArg'/>
        <see cref = 'swagger_petstore_v2.Order'/> store
        <see cref = 'swagger_petstore_v2.Pet'/> pet
        <see cref = 'swagger_petstore_v2.Tag'/>
        <see cref = 'swagger_petstore_v2.User'/> user
        <see cref = 'swagger_petstore_v2.addPet_405'/> pet
        <see cref = 'swagger_petstore_v2.createUser_default'/> user
        <see cref = 'swagger_petstore_v2.createUsersWithArrayInputReq'/> user
        <see cref = 'swagger_petstore_v2.createUsersWithArrayInput_default'/> user
        <see cref = 'swagger_petstore_v2.createUsersWithListInputReq'/> user
        <see cref = 'swagger_petstore_v2.createUsersWithListInput_default'/> user
        <see cref = 'swagger_petstore_v2.deleteOrderReq'/> store
        <see cref = 'swagger_petstore_v2.deleteOrder_400'/> store
        <see cref = 'swagger_petstore_v2.deleteOrder_404'/> store
        <see cref = 'swagger_petstore_v2.deletePetReq'/> pet
        <see cref = 'swagger_petstore_v2.deletePet_400'/> pet
        <see cref = 'swagger_petstore_v2.deletePet_404'/> pet
        <see cref = 'swagger_petstore_v2.deleteUserReq'/> user
        <see cref = 'swagger_petstore_v2.deleteUser_400'/> user
        <see cref = 'swagger_petstore_v2.deleteUser_404'/> user
        <see cref = 'swagger_petstore_v2.findPetsByStatusReq'/> pet
        <see cref = 'swagger_petstore_v2.findPetsByStatus_200'/> pet
        <see cref = 'swagger_petstore_v2.findPetsByStatus_400'/> pet
        <see cref = 'swagger_petstore_v2.findPetsByTagsReq'/> pet
        <see cref = 'swagger_petstore_v2.findPetsByTags_200'/> pet
        <see cref = 'swagger_petstore_v2.findPetsByTags_400'/> pet
        <see cref = 'swagger_petstore_v2.getInventory_200'/> store
        <see cref = 'swagger_petstore_v2.getOrderByIdReq'/> store
        <see cref = 'swagger_petstore_v2.getOrderById_400'/> store
        <see cref = 'swagger_petstore_v2.getOrderById_404'/> store
        <see cref = 'swagger_petstore_v2.getPetByIdReq'/> pet
        <see cref = 'swagger_petstore_v2.getPetById_400'/> pet
        <see cref = 'swagger_petstore_v2.getPetById_404'/> pet
        <see cref = 'swagger_petstore_v2.getUserByNameReq'/> user
        <see cref = 'swagger_petstore_v2.getUserByName_400'/> user
        <see cref = 'swagger_petstore_v2.getUserByName_404'/> user
        <see cref = 'swagger_petstore_v2.loginUserReq'/> user
        <see cref = 'swagger_petstore_v2.loginUser_200'/> user
        <see cref = 'swagger_petstore_v2.loginUser_400'/> user
        <see cref = 'swagger_petstore_v2.logoutUser_default'/> user
        <see cref = 'swagger_petstore_v2.placeOrder_400'/> store
        <see cref = 'swagger_petstore_v2.updatePetWithFormReq'/> pet
        <see cref = 'swagger_petstore_v2.updatePetWithForm_405'/> pet
        <see cref = 'swagger_petstore_v2.updatePet_400'/> pet
        <see cref = 'swagger_petstore_v2.updatePet_404'/> pet
        <see cref = 'swagger_petstore_v2.updatePet_405'/> pet
        <see cref = 'swagger_petstore_v2.updateUserReq'/> user
        <see cref = 'swagger_petstore_v2.updateUser_400'/> user
        <see cref = 'swagger_petstore_v2.updateUser_404'/> user
        <see cref = 'swagger_petstore_v2.uploadFileReq'/> pet
    */
    [Title(@"Swagger Petstore")]
    [Version(@"1.0.7")]
    [Description(@"This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.")]
    [Contact(@"", @"apiteam@swagger.io", @"")]
    [License(@"Apache 2.0", @"", @"http://www.apache.org/licenses/LICENSE-2.0.html")]
    [ExternalDocs(@"Find out more about Swagger", @"http://swagger.io/")]
    [TermsOfService(@"http://swagger.io/terms/")]
    [TagDefinition(@"pet", @"Everything about your Pets", @"", @"", @"")]
    [TagExternalDocs(@"pet", @"Find out more", @"http://swagger.io/")]
    [TagDefinition(@"store", @"Access to Petstore orders", @"", @"", @"")]
    [TagDefinition(@"user", @"Operations about user", @"", @"", @"")]
    [TagExternalDocs(@"user", @"Find out more about our store", @"http://swagger.io/")]
    public interface swagger_petstore_v2 {
        // 64-bit integers are `long` / `ulong` here, as `format: int64` says. A JSON number goes through a
        // double in JavaScript, so values above 2^53 never arrived there intact: if TypeScript hosts
        // matter and the values stay below that, `longJS` / `ulongJS` are the cheaper types.
        //
        // The document states ranges, never distributions. Where the values of an integer cluster - a
        // counter near its floor, a budget near its ceiling, a delta around zero - [A], [V] or [X] on
        // that field is the most valuable edit after conversion.

        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        [ApiKeyAuth(@"api_key", @"Header")]
        public class api_key { }

        [OAuth2AuthImplicit(@"https://petstore.swagger.io/oauth/authorize", @"")]
        public class petstore_auth {
            public enum petstore_authScope {
                /// <summary>read your pets</summary>
                read_pets,
                /// <summary>modify pets in your account</summary>
                write_pets,
            }
        }

        public class ApiResponse {
            int? code;
            string? Type;
            string? message;
        }

        public class Category {
            long? id;
            string? name;
        }

        public class Pet {
            long? id;
            Category? category;

            /// <summary>example: doggie</summary>
            string name;
            string[,,] photoUrls;
            Tag[,,]? tags;

            /// <summary>pet status in the store</summary>
            Pet.Status? status;

            public enum Status {
                available,
                pending,
                sold,
            }
        }

        public class Tag {
            long? id;
            string? name;
        }

        public class Order {
            long? id;
            long? petId;
            int? quantity;
            DateTime? shipDate;

            /// <summary>Order Status</summary>
            Order.Status? status;
            bool? complete;

            public enum Status {
                placed,
                approved,
                delivered,
            }
        }

        public class User {
            long? id;
            string? username;
            string? firstName;
            string? lastName;
            string? email;
            string? password;
            string? phone;

            /// <summary>User Status</summary>
            int? userStatus;
        }

        public class uploadFileReq {
            /// <summary>Additional data to pass to server</summary>
            string? additionalMetadata;

            /// <summary>file to upload</summary>
            [D(1_000_000 /*TODO: no size in the spec - set the real cap*/)]
            Binary[,,]? file;

            /// <summary>ID of pet to update</summary>
            long petId; // in: path
        }

        /// <summary>Invalid input</summary>
        public class addPet_405 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>Invalid ID supplied</summary>
        public class updatePet_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>Pet not found</summary>
        public class updatePet_404 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>Validation exception</summary>
        public class updatePet_405 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class findPetsByStatusReq {
            /// <summary>Status values that need to be considered for filter</summary>
            Pet.Status[,,] status; // in: query
        }

        /// <summary>successful operation</summary>
        public class findPetsByStatus_200 {
            Pet[,,] value;
        }

        /// <summary>Invalid status value</summary>
        public class findPetsByStatus_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class findPetsByTagsReq {
            /// <summary>Tags to filter by</summary>
            string[,,] tags; // in: query
        }

        /// <summary>successful operation</summary>
        public class findPetsByTags_200 {
            Pet[,,] value;
        }

        /// <summary>Invalid tag value</summary>
        public class findPetsByTags_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class getPetByIdReq {
            /// <summary>ID of pet to return</summary>
            long petId; // in: path
        }

        /// <summary>Invalid ID supplied</summary>
        public class getPetById_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>Pet not found</summary>
        public class getPetById_404 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class updatePetWithFormReq {
            /// <summary>Updated name of the pet</summary>
            string? name;

            /// <summary>Updated status of the pet</summary>
            string? status;

            /// <summary>ID of pet that needs to be updated</summary>
            long petId; // in: path
        }

        /// <summary>Invalid input</summary>
        public class updatePetWithForm_405 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class deletePetReq {
            string? api_key; // in: header

            /// <summary>Pet id to delete</summary>
            long petId; // in: path
        }

        /// <summary>Invalid ID supplied</summary>
        public class deletePet_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>Pet not found</summary>
        public class deletePet_404 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>successful operation</summary>
        public class getInventory_200 {
            Map<string, int> value;
        }

        /// <summary>Invalid Order</summary>
        public class placeOrder_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class getOrderByIdReq {
            /// <summary>ID of pet that needs to be fetched</summary>
            [MinMax(1, 10)]
            long orderId; // in: path
        }

        /// <summary>Invalid ID supplied</summary>
        public class getOrderById_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>Order not found</summary>
        public class getOrderById_404 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class deleteOrderReq {
            /// <summary>ID of the order that needs to be deleted</summary>
            [A(1)]
            long orderId; // in: path
        }

        /// <summary>Invalid ID supplied</summary>
        public class deleteOrder_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>Order not found</summary>
        public class deleteOrder_404 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>List of user object</summary>
        public class createUsersWithListInputReq {
            User[,,] body;
        }

        /// <summary>successful operation</summary>
        public class createUsersWithListInput_default {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class getUserByNameReq {
            /// <summary>The name that needs to be fetched. Use user1 for testing.</summary>
            string username; // in: path
        }

        /// <summary>Invalid username supplied</summary>
        public class getUserByName_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>User not found</summary>
        public class getUserByName_404 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>Updated user object</summary>
        public class updateUserReq : User {
            /// <summary>name that need to be updated</summary>
            string Username; // in: path
        }

        /// <summary>Invalid user supplied</summary>
        public class updateUser_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>User not found</summary>
        public class updateUser_404 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class deleteUserReq {
            /// <summary>The name that needs to be deleted</summary>
            string username; // in: path
        }

        /// <summary>Invalid username supplied</summary>
        public class deleteUser_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>User not found</summary>
        public class deleteUser_404 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class loginUserReq {
            /// <summary>The user name for login</summary>
            string username; // in: query

            /// <summary>The password for login in clear text</summary>
            string password; // in: query
        }

        /// <summary>successful operation</summary>
        public class loginUser_200 {
            string value;
        }

        /// <summary>HTTP response header `X-Rate-Limit`, parsed before the payload.</summary>
        public class X_Rate_Limit_int : HeaderFor<loginUser_200> {
            /// <summary>calls per hour allowed by the user</summary>
            int X_Rate_Limit;
        }

        /// <summary>Invalid username/password supplied</summary>
        public class loginUser_400 {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>successful operation</summary>
        public class logoutUser_default {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>List of user object</summary>
        public class createUsersWithArrayInputReq {
            User[,,] body;
        }

        /// <summary>successful operation</summary>
        public class createUsersWithArrayInput_default {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        /// <summary>successful operation</summary>
        public class createUser_default {
            [ContentType(@"application/json")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// https://petstore.swagger.io/v2
        /// http://petstore.swagger.io/v2
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        [Server(@"https://petstore.swagger.io/v2", @"", @"")]
        [Server(@"http://petstore.swagger.io/v2", @"", @"")]
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            public interface pet {
                // /pet/{petId}
                public interface petId {
                    public interface uploadImage {
                        /// <summary>
                        /// uploads an image
                        /// tags: pet
                        /// security: petstore_auth
                        /// </summary>
                        [HttpMethod(@"POST")]
                        [Tag(@"pet", @"Everything about your Pets")]
                        [TagExternalDocs(@"pet", @"Find out more", @"http://swagger.io/")]
                        [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                        (L____________,
                            /// <summary>successful operation</summary>
                            ApiResponse) uploadFile(uploadFileReq req);
                    }

                    /// <summary>
                    /// Find pet by ID
                    /// Returns a single pet
                    /// tags: pet
                    /// security: api_key
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"http://swagger.io/")]
                    [SecurityRequirement(@"api_key", @"")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        Pet,
                        /// <summary>Invalid ID supplied</summary>
                        getPetById_400,
                        /// <summary>Pet not found</summary>
                        getPetById_404) getPetById(getPetByIdReq req);

                    /// <summary>
                    /// Updates a pet in the store with form data
                    /// tags: pet
                    /// security: petstore_auth
                    /// </summary>
                    [HttpMethod(@"POST")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"http://swagger.io/")]
                    [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                    (L____________,
                        /// <summary>Invalid input</summary>
                        updatePetWithForm_405) updatePetWithForm(updatePetWithFormReq req);

                    /// <summary>
                    /// Deletes a pet
                    /// tags: pet
                    /// security: petstore_auth
                    /// </summary>
                    [HttpMethod(@"DELETE")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"http://swagger.io/")]
                    [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                    (L____________,
                        /// <summary>Invalid ID supplied</summary>
                        deletePet_400,
                        /// <summary>Pet not found</summary>
                        deletePet_404) deletePet(deletePetReq req);
                }

                /// <summary>
                /// Add a new pet to the store
                /// tags: pet
                /// security: petstore_auth
                /// </summary>
                [HttpMethod(@"POST")]
                [Tag(@"pet", @"Everything about your Pets")]
                [TagExternalDocs(@"pet", @"Find out more", @"http://swagger.io/")]
                [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                (L____________,
                    /// <summary>Invalid input</summary>
                    addPet_405) addPet(Pet req);

                /// <summary>
                /// Update an existing pet
                /// tags: pet
                /// security: petstore_auth
                /// </summary>
                [HttpMethod(@"PUT")]
                [Tag(@"pet", @"Everything about your Pets")]
                [TagExternalDocs(@"pet", @"Find out more", @"http://swagger.io/")]
                [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                (L____________,
                    /// <summary>Invalid ID supplied</summary>
                    updatePet_400,
                    /// <summary>Pet not found</summary>
                    updatePet_404,
                    /// <summary>Validation exception</summary>
                    updatePet_405) updatePet(Pet req);

                public interface findByStatus {
                    /// <summary>
                    /// Finds Pets by status
                    /// Multiple status values can be provided with comma separated strings
                    /// tags: pet
                    /// security: petstore_auth
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"http://swagger.io/")]
                    [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        findPetsByStatus_200,
                        /// <summary>Invalid status value</summary>
                        findPetsByStatus_400) findPetsByStatus(findPetsByStatusReq req);
                }

                public interface findByTags {
                    /// <summary>
                    /// Finds Pets by tags
                    /// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
                    /// tags: pet
                    /// security: petstore_auth
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"pet", @"Everything about your Pets")]
                    [TagExternalDocs(@"pet", @"Find out more", @"http://swagger.io/")]
                    [Obsolete(@"Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.")]
                    [SecurityRequirement(@"petstore_auth", @"write:pets,read:pets")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        findPetsByTags_200,
                        /// <summary>Invalid tag value</summary>
                        findPetsByTags_400) findPetsByTags(findPetsByTagsReq req);
                }
            }

            public interface store {
                public interface inventory {
                    /// <summary>
                    /// Returns pet inventories by status
                    /// Returns a map of status codes to quantities
                    /// tags: store
                    /// security: api_key
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"store", @"Access to Petstore orders")]
                    [SecurityRequirement(@"api_key", @"")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        getInventory_200) getInventory(NoArg _);
                }

                public interface order {
                    /// <summary>
                    /// Place an order for a pet
                    /// tags: store
                    /// </summary>
                    [HttpMethod(@"POST")]
                    [Tag(@"store", @"Access to Petstore orders")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        Order,
                        /// <summary>Invalid Order</summary>
                        placeOrder_400) placeOrder(Order req);

                    // /store/order/{orderId}
                    public interface orderId {
                        /// <summary>
                        /// Find purchase order by ID
                        /// For valid response try integer IDs with value >= 1 and &lt;= 10. Other values will generated exceptions
                        /// tags: store
                        /// </summary>
                        [HttpMethod(@"GET")]
                        [Tag(@"store", @"Access to Petstore orders")]
                        (L____________,
                            /// <summary>successful operation</summary>
                            Order,
                            /// <summary>Invalid ID supplied</summary>
                            getOrderById_400,
                            /// <summary>Order not found</summary>
                            getOrderById_404) getOrderById(getOrderByIdReq req);

                        /// <summary>
                        /// Delete purchase order by ID
                        /// For valid response try integer IDs with positive integer value. Negative or non-integer values will generate
                        /// API errors
                        /// tags: store
                        /// </summary>
                        [HttpMethod(@"DELETE")]
                        [Tag(@"store", @"Access to Petstore orders")]
                        (L____________,
                            /// <summary>Invalid ID supplied</summary>
                            deleteOrder_400,
                            /// <summary>Order not found</summary>
                            deleteOrder_404) deleteOrder(deleteOrderReq req);
                    }
                }
            }

            public interface user {
                public interface createWithList {
                    /// <summary>
                    /// Creates list of users with given input array
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"POST")]
                    [Tag(@"user", @"Operations about user")]
                    [TagExternalDocs(@"user", @"Find out more about our store", @"http://swagger.io/")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        createUsersWithListInput_default) createUsersWithListInput(createUsersWithListInputReq req);
                }

                // /user/{username}
                public interface username {
                    /// <summary>
                    /// Get user by user name
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"user", @"Operations about user")]
                    [TagExternalDocs(@"user", @"Find out more about our store", @"http://swagger.io/")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        User,
                        /// <summary>Invalid username supplied</summary>
                        getUserByName_400,
                        /// <summary>User not found</summary>
                        getUserByName_404) getUserByName(getUserByNameReq req);

                    /// <summary>
                    /// Updated user
                    /// This can only be done by the logged in user.
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"PUT")]
                    [Tag(@"user", @"Operations about user")]
                    [TagExternalDocs(@"user", @"Find out more about our store", @"http://swagger.io/")]
                    (L____________,
                        /// <summary>Invalid user supplied</summary>
                        updateUser_400,
                        /// <summary>User not found</summary>
                        updateUser_404) updateUser(updateUserReq req);

                    /// <summary>
                    /// Delete user
                    /// This can only be done by the logged in user.
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"DELETE")]
                    [Tag(@"user", @"Operations about user")]
                    [TagExternalDocs(@"user", @"Find out more about our store", @"http://swagger.io/")]
                    (L____________,
                        /// <summary>Invalid username supplied</summary>
                        deleteUser_400,
                        /// <summary>User not found</summary>
                        deleteUser_404) deleteUser(deleteUserReq req);
                }

                public interface login {
                    /// <summary>
                    /// Logs user into the system
                    /// tags: user
                    /// HTTP header on 200: X-Expires-After (String) - date in UTC when token expires
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"user", @"Operations about user")]
                    [TagExternalDocs(@"user", @"Find out more about our store", @"http://swagger.io/")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        loginUser_200,
                        /// <summary>Invalid username/password supplied</summary>
                        loginUser_400) loginUser(loginUserReq req);
                }

                public interface logout {
                    /// <summary>
                    /// Logs out current logged in user session
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"user", @"Operations about user")]
                    [TagExternalDocs(@"user", @"Find out more about our store", @"http://swagger.io/")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        logoutUser_default) logoutUser(NoArg _);
                }

                public interface createWithArray {
                    /// <summary>
                    /// Creates list of users with given input array
                    /// tags: user
                    /// </summary>
                    [HttpMethod(@"POST")]
                    [Tag(@"user", @"Operations about user")]
                    [TagExternalDocs(@"user", @"Find out more about our store", @"http://swagger.io/")]
                    (L____________,
                        /// <summary>successful operation</summary>
                        createUsersWithArrayInput_default) createUsersWithArrayInput(createUsersWithArrayInputReq req);
                }

                /// <summary>
                /// Create user
                /// This can only be done by the logged in user.
                /// tags: user
                /// </summary>
                [HttpMethod(@"POST")]
                [Tag(@"user", @"Operations about user")]
                [TagExternalDocs(@"user", @"Find out more about our store", @"http://swagger.io/")]
                (L____________,
                    /// <summary>successful operation</summary>
                    createUser_default) createUser(User req);
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class ApiKeyAuthAttribute : Attribute { public ApiKeyAuthAttribute(string Name = "", string In = "") { } }

        public class OAuth2AuthImplicitAttribute : Attribute { public OAuth2AuthImplicitAttribute(string AuthorizationUrl = "", string RefreshUrl = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ServerAttribute : Attribute { public ServerAttribute(string Url = "", string Description = "", string Name = "") { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagAttribute : Attribute { public TagAttribute(string Name = "", string Description = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagExternalDocsAttribute : Attribute { public TagExternalDocsAttribute(string TagName = "", string Description = "", string Url = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class SecurityRequirementAttribute : Attribute { public SecurityRequirementAttribute(string Scheme = "", string Scopes = "") { } }

        public class ContentTypeAttribute : Attribute { public ContentTypeAttribute(string MediaType = "") { } }

        public class ObsoleteAttribute : Attribute { public ObsoleteAttribute(string Message = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagDefinitionAttribute : Attribute { public TagDefinitionAttribute(string Name = "", string Description = "", string Summary = "", string Parent = "", string Kind = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }

        public class DescriptionAttribute : Attribute { public DescriptionAttribute(string Description = "") { } }

        public class ContactAttribute : Attribute { public ContactAttribute(string Name = "", string Email = "", string Url = "") { } }

        public class LicenseAttribute : Attribute { public LicenseAttribute(string Name = "", string Identifier = "", string Url = "") { } }

        public class ExternalDocsAttribute : Attribute { public ExternalDocsAttribute(string Description = "", string Url = "") { } }

        public class TermsOfServiceAttribute : Attribute { public TermsOfServiceAttribute(string Url = "") { } }
    }
}
