// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: tictactoe.yaml - Tic Tac Toe, version 1.0.0 (OpenAPI 3.1)
//          https://github.com/OAI/learn.openapis.org/blob/main/examples/v3.1/tictactoe.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'tictactoe.Code_200'/> Gameplay
        <see cref = 'tictactoe.Code_202'/> Gameplay
        <see cref = 'tictactoe.NoArg'/>
        <see cref = 'tictactoe.get_squareReq'/> Gameplay
        <see cref = 'tictactoe.get_square_200'/> Gameplay
        <see cref = 'tictactoe.get_square_400'/> Gameplay
        <see cref = 'tictactoe.put_squareReq'/> Gameplay
        <see cref = 'tictactoe.put_square_400'/> Gameplay
        <see cref = 'tictactoe.status'/> Gameplay | webhook
    */
    [Title(@"Tic Tac Toe")]
    [Version(@"1.0.0")]
    [Description(@"This API allows writing down marks on a Tic Tac Toe board
and requesting the state of the board or of individual squares.")]
    [TagDefinition(@"Gameplay", @"", @"", @"", @"")]
    public interface tictactoe {
        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        /// <summary>API key provided in console</summary>
        [ApiKeyAuth(@"api-key", @"Header")]
        public class defaultApiKey { }

        /// <summary>Basic HTTP Authentication</summary>
        [BasicAuth]
        public class basicHttpAuthentication { }

        /// <summary>Bearer token using a JWT</summary>
        [BearerAuth(@"JWT")]
        public class bearerHttpAuthentication { }

        [OAuth2AuthClientCredentials(@"https://learn.openapis.org/oauth/2.0/token", @"")]
        public class app2AppOauth {
            public enum app2AppOauthScope {
                /// <summary>Read the board</summary>
                board_read,
                one_more_field, // filler: an AdHoc enum needs at least two members
            }
        }

        [OAuth2AuthAuthorizationCode(@"https://learn.openapis.org/oauth/2.0/auth", @"https://learn.openapis.org/oauth/2.0/token", @"")]
        public class user2AppOauth {
            public enum user2AppOauthScope {
                /// <summary>Read the board</summary>
                board_read,
                /// <summary>Write to the board</summary>
                board_write,
            }
        }

        /// <summary>Possible values for a board square. `.` means empty square.</summary>
        [Example(@".")]
        public enum mark {
            ˍ, // .
            X,
            O,
        }

        /// <summary>Winner of the game. `.` means nobody has won yet.</summary>
        [Example(@".")]
        public enum winner {
            ˍ, // .
            X,
            O,
        }

        public class errorMessage {
            /// <summary>A text message describing an error</summary>
            [D(+256)]
            string TYPEDEF;
        }

        public class coordinate {
            /// <summary>example: 1</summary>
            [MinMax(1, 3)]
            int TYPEDEF;
        }

        public class board {
            [D(3)]
            mark[][] TYPEDEF;
        }

        public class status {
            winner? winner;
            board? board;
        }

        public class parameters {
            /// <summary>Board row (vertical coordinate)</summary>
            coordinate row; // in: path

            /// <summary>Board column (horizontal coordinate)</summary>
            coordinate column; // in: path
        }

        /// <see cref="parameters.row"/>+
        /// <see cref="parameters.column"/>+
        public class get_squareReq { }

        /// <summary>OK</summary>
        public class get_square_200 {
            mark value;
        }

        /// <summary>The provided parameters are incorrect</summary>
        public class get_square_400 {
            errorMessage value;
        }

        public class Code_200 { }

        /// <see cref="parameters.row"/>+
        /// <see cref="parameters.column"/>+
        public class put_squareReq {
            mark body;

            /// <summary>Progress URL that should be called if asynchronous response is returned</summary>
            string? progressUrl; // in: header
        }

        public class Code_202 { }

        /// <summary>The provided parameters are incorrect</summary>
        public class put_square_400 {
            errorMessage value;
        }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            // /board
            public interface Board {
                /// <summary>
                /// Get the whole board
                /// Retrieves the current state of the board and the winner.
                /// tags: Gameplay
                /// security: defaultApiKey, app2AppOauth
                /// operationId: get-board
                /// </summary>
                [HttpMethod(@"GET")]
                [Tag(@"Gameplay", @"")]
                [SecurityRequirement(@"defaultApiKey", @"")]
                [SecurityRequirement(@"app2AppOauth", @"board:read")]
                (L____________,
                    /// <summary>OK</summary>
                    status) get_board(NoArg _);

                // /board/{row}
                public interface row {
                    // /board/{row}/{column}
                    public interface column {
                        /// <summary>
                        /// Get a single board square
                        /// Retrieves the requested square.
                        /// tags: Gameplay
                        /// security: bearerHttpAuthentication, user2AppOauth
                        /// link markSquare (after 200) → put-square: row = $request.path.row, column = $request.path.column - Operation
                        /// to use if the mark value returned indicates the square is empty
                        /// operationId: get-square
                        /// </summary>
                        [HttpMethod(@"GET")]
                        [Tag(@"Gameplay", @"")]
                        [SecurityRequirement(@"bearerHttpAuthentication", @"")]
                        [SecurityRequirement(@"user2AppOauth", @"board:read")]
                        public interface get_square : Actor {
                            int MaxActiveInstances => UNLIMITED;

                            [L____________<Return_get_square, get_squareReq>]
                            struct Call_get_square { }

                            [____________R<org.openapi.tictactoe.ClientServerConnection.Board.row.column.put_square.Call_put_square, get_square_200>]
                            [____________R<End, get_square_400>]
                            struct Return_get_square { }
                        }

                        /// <summary>
                        /// Set a single board square
                        /// Places a mark on the board and retrieves the whole board and the winner (if any).
                        /// tags: Gameplay
                        /// security: bearerHttpAuthentication, user2AppOauth
                        /// callback statusCallback: POST {$request.header.progressUrl} - Status of mark operation
                        /// HTTP header on 202: Location (String) - Callback URL
                        /// operationId: put-square
                        /// </summary>
                        [HttpMethod(@"PUT")]
                        [Tag(@"Gameplay", @"")]
                        [SecurityRequirement(@"bearerHttpAuthentication", @"")]
                        [SecurityRequirement(@"user2AppOauth", @"board:write")]
                        public interface put_square : Actor {
                            int MaxActiveInstances => UNLIMITED;

                            [L____________<Return_put_square, put_squareReq>]
                            struct Call_put_square { }

                            [____________R<CallbackState_put_square, (status, Code_202, put_square_400)>]
                            struct Return_put_square { }

                            [l____________<Code_200>]
                            [____________r<status>]
                            [L____________<End, NoArg>]
                            struct CallbackState_put_square { }
                        }
                    }
                }
            }
        }

        /// <summary>The receiver of the webhooks.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Subscriber : Host { }

        interface ServerSubscriberConnection : Connects<Server, Subscriber> {
            public interface markStatus {
                /// <summary>
                /// Status of mark operation
                /// Provides the status of the mark operation on completion
                /// </summary>
                [HttpMethod(@"POST")]
                (L____________,
                    /// <summary>Mark operation has completed successfully</summary>
                    status) markOperationWebhook(NoArg _);
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class ApiKeyAuthAttribute : Attribute { public ApiKeyAuthAttribute(string Name = "", string In = "") { } }

        public class BasicAuthAttribute : Attribute { public BasicAuthAttribute() { } }

        public class BearerAuthAttribute : Attribute { public BearerAuthAttribute(string BearerFormat = "") { } }

        public class OAuth2AuthClientCredentialsAttribute : Attribute { public OAuth2AuthClientCredentialsAttribute(string TokenUrl = "", string RefreshUrl = "") { } }

        public class OAuth2AuthAuthorizationCodeAttribute : Attribute { public OAuth2AuthAuthorizationCodeAttribute(string AuthorizationUrl = "", string TokenUrl = "", string RefreshUrl = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ExampleAttribute : Attribute { public ExampleAttribute(string Value = "") { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagAttribute : Attribute { public TagAttribute(string Name = "", string Description = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class SecurityRequirementAttribute : Attribute { public SecurityRequirementAttribute(string Scheme = "", string Scopes = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagDefinitionAttribute : Attribute { public TagDefinitionAttribute(string Name = "", string Description = "", string Summary = "", string Parent = "", string Kind = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }

        public class DescriptionAttribute : Attribute { public DescriptionAttribute(string Description = "") { } }
    }
}
