// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: uspto.yaml - USPTO Data Set API, version 1.0.0 (OpenAPI 3.0)
//          https://github.com/OAI/learn.openapis.org/blob/main/examples/v3.0/uspto.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'uspto.Code_404'/> search
        <see cref = 'uspto.NoArg'/>
        <see cref = 'uspto.dataSetList'/> metadata
        <see cref = 'uspto.dataSetList.Apis'/>
        <see cref = 'uspto.list_searchable_fieldsReq'/> metadata
        <see cref = 'uspto.list_searchable_fields_200'/> metadata
        <see cref = 'uspto.list_searchable_fields_404'/> metadata
        <see cref = 'uspto.perform_searchReq'/> search
        <see cref = 'uspto.perform_search_200'/> search
    */
    [Title(@"USPTO Data Set API")]
    [Version(@"1.0.0")]
    [Description(@"The Data Set API (DSAPI) allows the public users to discover and search USPTO exported data sets. This is a generic API that allows USPTO users to make any CSV based data files searchable through API. With the help of GET call, it returns the list of data fields that are searchable. With the help of POST call, data can be fetched based on the filters on the field names. Please note that POST call is used to search the actual data. The reason for the POST call is that it allows users to specify any complex search criteria without worry about the GET size limitations as well as encoding of the input parameters.")]
    [Contact(@"Open Data Portal", @"developer@uspto.gov", @"https://developer.uspto.gov/")]
    [TagDefinition(@"metadata", @"Find out about the data sets", @"", @"", @"")]
    [TagDefinition(@"search", @"Search a data set", @"", @"", @"")]
    public interface uspto {
        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        public class dataSetList {
            int? total;
            dataSetList.Apis[,,]? apis;

            public class Apis {
                /// <summary>To be used as a dataset parameter value</summary>
                string? apiKey;

                /// <summary>To be used as a version parameter value</summary>
                string? apiVersionNumber;

                /// <summary>The URL describing the dataset's fields</summary>
                [Format(@"uri-reference")]
                string? apiUrl;

                /// <summary>A URL to the API console for each API</summary>
                [Format(@"uri-reference")]
                string? apiDocumentationUrl;
            }
        }

        public class list_searchable_fieldsReq {
            /// <summary>
            /// Name of the dataset.
            /// example: oa_citations
            /// </summary>
            string dataset; // in: path

            /// <summary>
            /// Version of the dataset.
            /// example: v1
            /// </summary>
            string version; // in: path
        }

        /// <summary>The dataset API for the given version is found and it is accessible to consume.</summary>
        public class list_searchable_fields_200 {
            string value;
        }

        /// <summary>
        /// The combination of dataset name and version is not found in the system or it is not published yet to be
        /// consumed by public.
        /// </summary>
        public class list_searchable_fields_404 {
            string value;
        }

        public class perform_searchReq {
            /// <summary>
            /// Uses Lucene Query Syntax in the format of propertyName:value, propertyName:[num1 TO num2] and date range
            /// format: propertyName:[yyyyMMdd TO yyyyMMdd]. In the response please see the 'docs' element which has the list
            /// of record objects. Each record structure would consist of all the fields and their corresponding values.
            /// </summary>
            [Default(@"*:*")]
            string criteria;

            /// <summary>Starting record number. Default value is 0.</summary>
            [Default(0)]
            int? start;

            /// <summary>
            /// Specify number of rows to be returned. If you run the search with default values, in the response you will see
            /// 'numFound' attribute which will tell the number of records available in the dataset.
            /// </summary>
            [Default(100)]
            int? rows;

            /// <summary>Version of the dataset.</summary>
            [Default(@"v1")]
            string version; // in: path

            /// <summary>Name of the dataset. In this case, the default value is oa_citations</summary>
            [Default(@"oa_citations")]
            string dataset; // in: path
        }

        /// <summary>successful operation</summary>
        public class perform_search_200 {
            Map<string, Binary[,,]>[,,] value; // any JSON in the spec: carried as raw bytes
        }

        public class Code_404 { }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// {scheme}://developer.uspto.gov/ds-api
        ///     Variable 'scheme': https://swagger.io/specification/#server-variable-object
        ///     The Data Set API is accessible via https and http
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        [Server(@"{scheme}://developer.uspto.gov/ds-api", @"", @"")]
        [ServerVariable(@"{scheme}://developer.uspto.gov/ds-api", @"scheme", @"https", @"The Data Set API is accessible via https and http", @"https|http")]
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            /// <summary>
            /// List available data sets
            /// tags: metadata
            /// operationId: list-data-sets
            /// </summary>
            [HttpMethod(@"GET")]
            [Tag(@"metadata", @"Find out about the data sets")]
            (L____________,
                /// <summary>Returns a list of data sets</summary>
                dataSetList) list_data_sets(NoArg _);

            // /{dataset}
            public interface dataset {
                // /{dataset}/{version}
                public interface version {
                    public interface fields {
                        /// <summary>
                        /// Provides the general information about the API and the list of fields that can be used to query the dataset.
                        /// This GET API returns the list of all the searchable field names that are in the oa_citations. Please see the
                        /// 'fields' attribute which returns an array of field names. Each field or a combination of fields can be
                        /// searched using the syntax options shown below.
                        /// tags: metadata
                        /// operationId: list-searchable-fields
                        /// </summary>
                        [HttpMethod(@"GET")]
                        [Tag(@"metadata", @"Find out about the data sets")]
                        (L____________,
                            /// <summary>The dataset API for the given version is found and it is accessible to consume.</summary>
                            list_searchable_fields_200,
                            /// <summary>
                            /// The combination of dataset name and version is not found in the system or it is not published yet to be
                            /// consumed by public.
                            /// </summary>
                            list_searchable_fields_404) list_searchable_fields(list_searchable_fieldsReq req);
                    }

                    public interface records {
                        /// <summary>
                        /// Provides search capability for the data set with the given search criteria.
                        /// This API is based on Solr/Lucene Search. The data is indexed using SOLR. This GET API returns the list of all
                        /// the searchable field names that are in the Solr Index. Please see the 'fields' attribute which returns an
                        /// array of field names. Each field or a combination of fields can be searched using the Solr/Lucene Syntax.
                        /// Please refer https://lucene.apache.org/core/3_6_2/queryparsersyntax.html#Overview for the query syntax. List
                        /// of field names that are searchable can be determined using above GET api.
                        /// tags: search
                        /// operationId: perform-search
                        /// </summary>
                        [HttpMethod(@"POST")]
                        [Tag(@"search", @"Search a data set")]
                        (L____________,
                            /// <summary>successful operation</summary>
                            perform_search_200,
                            /// <summary>No matching record found for the given criteria.</summary>
                            Code_404) perform_search(perform_searchReq req);
                    }
                }
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ServerAttribute : Attribute { public ServerAttribute(string Url = "", string Description = "", string Name = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ServerVariableAttribute : Attribute { public ServerVariableAttribute(string ServerUrl = "", string Name = "", string Default = "", string Description = "", string Enum = "") { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagAttribute : Attribute { public TagAttribute(string Name = "", string Description = "") { } }

        public class DefaultAttribute : Attribute { public DefaultAttribute(double value) { } public DefaultAttribute(long value) { } public DefaultAttribute(string value) { } public DefaultAttribute(bool value) { } }

        public class FormatAttribute : Attribute { public FormatAttribute(string Name = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagDefinitionAttribute : Attribute { public TagDefinitionAttribute(string Name = "", string Description = "", string Summary = "", string Parent = "", string Kind = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }

        public class DescriptionAttribute : Attribute { public DescriptionAttribute(string Description = "") { } }

        public class ContactAttribute : Attribute { public ContactAttribute(string Name = "", string Email = "", string Url = "") { } }
    }
}
