// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: webhook-example.yaml - Webhook Example, version 1.0.0 (OpenAPI 3.1)
//          https://github.com/OAI/learn.openapis.org/blob/main/examples/v3.1/webhook-example.yaml
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'webhook_example.Code_200'/> webhook
        <see cref = 'webhook_example.NoArg'/>
        <see cref = 'webhook_example.Pet'/> webhook
    */
    [Title(@"Webhook Example")]
    [Version(@"1.0.0")]
    public interface webhook_example {
        // 64-bit integers are `long` / `ulong` here, as `format: int64` says. A JSON number goes through a
        // double in JavaScript, so values above 2^53 never arrived there intact: if TypeScript hosts
        // matter and the values stay below that, `longJS` / `ulongJS` are the cheaper types.
        //
        // The document states ranges, never distributions. Where the values of an integer cluster - a
        // counter near its floor, a budget near its ceiling, a delta around zero - [A], [V] or [X] on
        // that field is the most valuable edit after conversion.

        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        public class Pet {
            long id;
            string name;
            string? tag;
        }

        public class Code_200 { }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Server : Host { }

        /// <summary>The receiver of the webhooks.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Subscriber : Host { }

        interface ServerSubscriberConnection : Connects<Server, Subscriber> {
            [HttpMethod(@"POST")]
            (L____________,
                /// <summary>Return a 200 status to indicate that the data was received successfully</summary>
                Code_200) newPet(Pet req);
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }
    }
}
