// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: coverage.yaml - Coverage, version 2.0.0 (OpenAPI 3.1)
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'coverage.Address'/>
        <see cref = 'coverage.Code_200'/> webhook
        <see cref = 'coverage.Code_204'/> orders
        <see cref = 'coverage.Code_304'/> orders
        <see cref = 'coverage.Code_default'/> orders
        <see cref = 'coverage.Customer'/>
        <see cref = 'coverage.Event'/> events
        <see cref = 'coverage.Invalid'/> orders
        <see cref = 'coverage.LegacyOrder'/>
        <see cref = 'coverage.Line'/>
        <see cref = 'coverage.NoArg'/>
        <see cref = 'coverage.NotFound'/> orders
        <see cref = 'coverage.Order'/>
        <see cref = 'coverage.Order.CUstomer'/>
        <see cref = 'coverage.Order.PAyment'/>
        <see cref = 'coverage.Order.Shipping'/>
        <see cref = 'coverage.Order_Read'/> orders
        <see cref = 'coverage.Order_Write'/>
        <see cref = 'coverage.Payment'/> orders
        <see cref = 'coverage.Problem'/>
        <see cref = 'coverage.Report'/> events
        <see cref = 'coverage.ReportLine'/> events
        <see cref = 'coverage.Unauthorized'/> events | orders
        <see cref = 'coverage.createOrderReq'/> orders
        <see cref = 'coverage.getInvoiceReq'/> orders
        <see cref = 'coverage.getInvoice_200'/> orders
        <see cref = 'coverage.getOrderReq'/> orders
        <see cref = 'coverage.listOrdersReq'/> orders
        <see cref = 'coverage.listOrders_200'/> orders
        <see cref = 'coverage.orderShippedReq'/> webhook
        <see cref = 'coverage.replaceOrderReq'/> orders
    */
    [Title(@"Coverage")]
    [Version(@"2.0.0")]
    [Summary(@"Every feature once")]
    [Description(@"A document that uses each part of the specification the converter maps.")]
    [Contact(@"Team", @"team@example.com", @"https://example.com/")]
    [License(@"Apache 2.0", @"Apache-2.0", @"")]
    [ExternalDocs(@"The manual", @"https://example.com/docs")]
    [TermsOfService(@"https://example.com/terms")]
    [Extension(@"x-audience", @"internal")]
    [TagDefinition(@"orders", @"Orders of a shop", @"", @"", @"")]
    [TagExternalDocs(@"orders", @"", @"https://example.com/orders")]
    [TagDefinition(@"events", @"", @"", @"", @"")]
    public interface coverage {
        // 64-bit integers are `long` / `ulong` here, as `format: int64` says. A JSON number goes through a
        // double in JavaScript, so values above 2^53 never arrived there intact: if TypeScript hosts
        // matter and the values stay below that, `longJS` / `ulongJS` are the cheaper types.
        //
        // The document states ranges, never distributions. Where the values of an integer cluster - a
        // counter near its floor, a budget near its ceiling, a delta around zero - [A], [V] or [X] on
        // that field is the most valuable edit after conversion.

        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        /// <summary>Shared error pack set - error schemas reused across operations.</summary>
        public interface StandardErrors : _<(NotFound, Unauthorized)> { }

        // ═════════════════════════ packs ═════════════════════════

        [ApiKeyAuth(@"X-Api-Key", @"Header")]
        public class apiKey { }

        /// <summary>The OAuth of the shop</summary>
        [OAuth2AuthClientCredentials(@"https://example.com/token", @"")]
        public class oauth {
            public enum oauthScope {
                /// <summary>Read the orders</summary>
                orders_read,
                /// <summary>Change the orders</summary>
                orders_write,
            }
        }

        /// <summary>Where an order is</summary>
        public enum OrderStatus {
            New, // new
            paid,
            shipped,
        }

        public enum Priority {
            /// <summary>Whenever</summary>
            LOW = 0,
            /// <summary>In its turn</summary>
            NORMAL = 1,
            /// <summary>Before the others</summary>
            HIGH = 2,
        }

        public class OrderId {
            /// <summary>The id of an order</summary>
            Uuid TYPEDEF;
        }

        public class Quantity {
            [MinMax(1, 999)]
            ushort TYPEDEF;
        }

        public class Orders {
            [D(100)]
            Order[,,] TYPEDEF;
        }

        public class Tags {
            [D(+16)]
            [Val: D(+64)]
            Map<string, string> TYPEDEF;
        }

        public class Order {
            public const string kind = @"order";

            public const int version = 2;
            OrderId id;
            OrderStatus status;
            Priority? priority;

            [ReadOnly]
            DateTime? placed;
            Date? due;
            TimeOfDay? openFrom;
            DurationDefault? validFor;

            [Format(@"uri")]
            [WriteOnly]
            string? callbackUrl;

            [D(+254)]
            [Validate(Regex = @"^.+@.+$", MinLength = 3)]
            [Format(@"email")]
            string? email;

            [D(4096)]
            Binary[,,]? receipt;

            /// <summary>
            /// constraint: minimum 0.0
            /// constraint: a multiple of 0.01
            /// </summary>
            double? total;
            float? weight;
            uint? flags;
            ulong? revision;
            short? delta;

            [MinMax(0, 127)]
            sbyte? level;

            /// <summary>constraint: at least 1 items</summary>
            Line[,,] lines;

            [D(5)]
            [MinMax(0, 100)]
            int[,,]? discounts;

            [D(+200)]
            string?[,,]? notes;
            Tags? tags;

            [Val: MinMax(0, 10)]
            Map<string, int>? scores;
            Order.CUstomer? customer;
            Order.Shipping? shipping;
            Order.PAyment? payment;
            bool? gift; // typed with a pack that carries no value: being there is all it says

            public class CUstomer {
                /// <summary>The id of the customer</summary>
                string? OneOf_OneOf0;
                Customer? OneOf_Customer;
            }

            public class Shipping : Address {
                string? instructions;
            }

            public class PAyment {
                Order.PAyment.Method? method;
                bool? paid;

                public enum Method {
                    card,
                    cash,
                }
            }
        }

        public class LegacyOrder {
            int? Number;
        }

        public class Line {
            string sku;
            Quantity quantity;
            double? price;

            /// <summary>every other property of the object</summary>
            Map<string, string> additionalProperties;
        }

        public class Customer {
            string? id;
            string? name;
        }

        public class Address {
            string? street;
            string? city;
        }

        public class Gift {
            public const string kind = @"gift";
        }

        public class Payment {
            OrderId? order;
            double? amount;
        }

        public class Problem {
            int? code;
            string? message;
        }

        public class Event {
            DateTime? at;
            OrderId? order;
            OrderStatus? status;
        }

        public class Report {
            ReportLine[,,]? lines;
        }

        public class ReportLine {
            Date? day;
            int? orders;
        }

        /// <summary>
        /// Write-projection of Order (client → server: readOnly fields blocked). SSOT: the fields live in Order;
        /// rename/retype there and this projection follows.
        /// </summary>
        /// <see cref="Order.placed"/>-
        public class Order_Write : Order { }

        /// <summary>
        /// Read-projection of Order (server → client: writeOnly fields blocked). SSOT: the fields live in Order;
        /// rename/retype there and this projection follows.
        /// </summary>
        /// <see cref="Order.callbackUrl"/>-
        public class Order_Read : Order { }

        /// <summary>No valid credentials</summary>
        public class Unauthorized { }

        /// <summary>No such order</summary>
        public class NotFound : Problem { }

        /// <summary>The order cannot be accepted</summary>
        public class Invalid : Problem { }

        public class parameters {
            /// <summary>The shop</summary>
            [D(+32)]
            string tenant; // in: header

            /// <summary>The size of a page</summary>
            [MinMax(1, 100)]
            [Default(20)]
            int? limit; // in: query

            [A(0)]
            long? offset; // in: query
        }

        [Validate(Regex = @"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$", MaxLength = 36)]
        public class Uuid {
            ulong hi;
            ulong lo;
        }

        public class Date : DateTimeDef {
            public TimeSpan precision => TimeSpan.FromDays(1);
        }

        public class TimeOfDay : Duration {
            public long     max       => 86_399_999; // the last millisecond of a day
            public TimeSpan precision => TimeSpan.FromMilliseconds(1);
        }

        public class DurationDefault : Duration { }

        [GlobalSecurity(@"apiKey", @"")]
        public class global { }

        /// <see cref="parameters.tenant"/>+
        /// <see cref="parameters.limit"/>+
        /// <see cref="parameters.offset"/>+
        public class listOrdersReq {
            /// <summary>example: paid</summary>
            OrderStatus? status; // in: query
            Date? since; // in: query
            string? If_None_Match; // in: header
        }

        /// <summary>A page of orders</summary>
        public class listOrders_200 {
            Orders value;
        }

        /// <summary>HTTP response header `X-Total-Count`, parsed before the payload.</summary>
        public class X_Total_Count_long : HeaderFor<listOrders_200> {
            /// <summary>How many there are</summary>
            long X_Total_Count;
        }

        public class Code_304 { }

        public class Code_default { }

        public class Code_204 { }

        /// <summary>
        /// The order to place
        /// The body is also offered as application/xml: one form is carried.
        /// </summary>
        /// <see cref="parameters.tenant"/>+
        public class createOrderReq : Order_Write { }

        public class getOrderReq {
            OrderId id; // in: path
        }

        public class replaceOrderReq : Order_Write {
            OrderId Id; // in: path
        }

        public class getInvoiceReq {
            OrderId id; // in: path
        }

        /// <summary>The invoice as a document</summary>
        public class getInvoice_200 {
            [ContentType(@"application/pdf")]
            [S(1_000_000_000 /*TODO: set the real cap*/)] File value;
        }

        public class orderShippedReq : Order_Read {
            [D(1_000_000 /*TODO: no size in the spec - set the real cap*/)]
            Binary[,,] X_Signature; // in: header
        }

        public class Code_200 { }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// https://{region}.example.com/v2
        ///     Production
        ///     Variable 'region': https://swagger.io/specification/#server-variable-object
        ///     The region
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        [Server(@"https://{region}.example.com/v2", @"Production", @"")]
        [ServerVariable(@"https://{region}.example.com/v2", @"region", @"eu", @"The region", @"eu|us")]
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            /// <summary>
            /// The orders
            /// Everything about the orders of a shop.
            /// </summary>
            public interface orders {
                /// <summary>
                /// Lists the orders
                /// tags: orders
                /// security: none
                /// link first (after 200) → getOrder: id = $response.body#/0/id - The first order of the page
                /// </summary>
                [HttpMethod(@"GET")]
                [Tag(@"orders", @"Orders of a shop")]
                [TagExternalDocs(@"orders", @"", @"https://example.com/orders")]
                [Server(@"https://reports.example.com", @"The reporting replica", @"")]
                [Extension(@"x-rate-limited", @"true")]
                public interface listOrders : Actor {
                    int MaxActiveInstances => UNLIMITED;

                    [L____________<Return_listOrders, listOrdersReq>]
                    struct Call_listOrders { }

                    [____________R<org.openapi.coverage.ClientServerConnection.orders.id.getOrder.Call_getOrder, listOrders_200>]
                    [____________R<End, (Code_304, StandardErrors, Code_default)>]
                    struct Return_listOrders { }
                }

                /// <summary>
                /// tags: orders
                /// callback paid: POST {$request.body#/callbackUrl} - Tells that the order was paid
                /// </summary>
                [HttpMethod(@"POST")]
                [Tag(@"orders", @"Orders of a shop")]
                [TagExternalDocs(@"orders", @"", @"https://example.com/orders")]
                public interface createOrder : Actor {
                    int MaxActiveInstances => UNLIMITED;

                    [L____________<Return_createOrder, createOrderReq>]
                    struct Call_createOrder { }

                    [____________R<CallbackState_createOrder, (Order_Read, StandardErrors, Invalid)>]
                    struct Return_createOrder { }

                    [l____________<Code_204>]
                    [____________r<Payment>]
                    [L____________<End, NoArg>]
                    struct CallbackState_createOrder { }
                }

                // /orders/{id}
                public interface id {
                    /// <summary>tags: orders</summary>
                    [HttpMethod(@"GET")]
                    [Tag(@"orders", @"Orders of a shop")]
                    [TagExternalDocs(@"orders", @"", @"https://example.com/orders")]
                    public interface getOrder : Actor {
                        int MaxActiveInstances => UNLIMITED;

                        [L____________<Return_getOrder, getOrderReq>]
                        struct Call_getOrder { }

                        [____________R<End, (Order_Read, StandardErrors)>]
                        struct Return_getOrder { }
                    }

                    /// <summary>tags: orders</summary>
                    [HttpMethod(@"PUT")]
                    [Tag(@"orders", @"Orders of a shop")]
                    [TagExternalDocs(@"orders", @"", @"https://example.com/orders")]
                    (L____________,
                        /// <summary>Replaced</summary>
                        Order_Read,
                        /// <summary>shared errors</summary>
                        StandardErrors) replaceOrder(replaceOrderReq req);

                    public interface invoice {
                        /// <summary>tags: orders</summary>
                        [HttpMethod(@"GET")]
                        [Tag(@"orders", @"Orders of a shop")]
                        [TagExternalDocs(@"orders", @"", @"https://example.com/orders")]
                        (L____________,
                            /// <summary>The invoice as a document</summary>
                            getInvoice_200,
                            /// <summary>shared errors</summary>
                            StandardErrors) getInvoice(getInvoiceReq req);
                    }
                }
            }

            public interface events {
                /// <summary>
                /// The events of the shop, as they happen
                /// tags: events
                /// </summary>
                [HttpMethod(@"GET")]
                [Tag(@"events", @"")]
                public interface watchEvents : Actor {
                    int MaxActiveInstances => UNLIMITED;

                    [L____________<Return_watchEvents, NoArg>]
                    struct Call_watchEvents { }

                    [____________r<Event>]
                    [____________R<End, (StandardErrors, NoArg)>]
                    struct Return_watchEvents { }
                }
            }

            public interface report {
                /// <summary>
                /// A report, whole or line by line
                /// tags: events
                /// </summary>
                [HttpMethod(@"GET")]
                [Tag(@"events", @"")]
                public interface getReport : Actor {
                    int MaxActiveInstances => UNLIMITED;

                    [L____________<Return_getReport, NoArg>]
                    struct Call_getReport { }

                    [____________r<ReportLine>]
                    [____________R<End, (Report, NoArg)>]
                    struct Return_getReport { }
                }
            }
        }

        /// <summary>The receiver of the webhooks.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Subscriber : Host { }

        interface ServerSubscriberConnection : Connects<Server, Subscriber> {
            [HttpMethod(@"POST")]
            (L____________,
                /// <summary>Received</summary>
                Code_200) orderShipped(orderShippedReq req);
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class ApiKeyAuthAttribute : Attribute { public ApiKeyAuthAttribute(string Name = "", string In = "") { } }

        public class OAuth2AuthClientCredentialsAttribute : Attribute { public OAuth2AuthClientCredentialsAttribute(string TokenUrl = "", string RefreshUrl = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class GlobalSecurityAttribute : Attribute { public GlobalSecurityAttribute(string Scheme = "", string Scopes = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ServerAttribute : Attribute { public ServerAttribute(string Url = "", string Description = "", string Name = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ServerVariableAttribute : Attribute { public ServerVariableAttribute(string ServerUrl = "", string Name = "", string Default = "", string Description = "", string Enum = "") { } }

        public class ReadOnlyAttribute : Attribute { public ReadOnlyAttribute() { } }

        public class FormatAttribute : Attribute { public FormatAttribute(string Name = "") { } }

        public class WriteOnlyAttribute : Attribute { public WriteOnlyAttribute() { } }

        [AttributeUsage(AttributeTargets.All)] public class ValidateAttribute : Attribute { public string Regex { get; set; } = ""; public long MinLength { get; set; } = -1; public long MaxLength { get; set; } = -1; }

        public class DefaultAttribute : Attribute { public DefaultAttribute(double value) { } public DefaultAttribute(long value) { } public DefaultAttribute(string value) { } public DefaultAttribute(bool value) { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagAttribute : Attribute { public TagAttribute(string Name = "", string Description = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagExternalDocsAttribute : Attribute { public TagExternalDocsAttribute(string TagName = "", string Description = "", string Url = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ExtensionAttribute : Attribute { public ExtensionAttribute(string Key = "", string Value = "") { } }

        public class ContentTypeAttribute : Attribute { public ContentTypeAttribute(string MediaType = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagDefinitionAttribute : Attribute { public TagDefinitionAttribute(string Name = "", string Description = "", string Summary = "", string Parent = "", string Kind = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }

        public class SummaryAttribute : Attribute { public SummaryAttribute(string Summary = "") { } }

        public class DescriptionAttribute : Attribute { public DescriptionAttribute(string Description = "") { } }

        public class ContactAttribute : Attribute { public ContactAttribute(string Name = "", string Email = "", string Url = "") { } }

        public class LicenseAttribute : Attribute { public LicenseAttribute(string Name = "", string Identifier = "", string Url = "") { } }

        public class ExternalDocsAttribute : Attribute { public ExternalDocsAttribute(string Description = "", string Url = "") { } }

        public class TermsOfServiceAttribute : Attribute { public TermsOfServiceAttribute(string Url = "") { } }
    }
}
