// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: edge-cases.yaml - Edge cases, version 1 (OpenAPI 3.0)
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'edge_cases.CLient'/>
        <see cref = 'edge_cases.Circle'/>
        <see cref = 'edge_cases.Code_204'/>
        <see cref = 'edge_cases.Code_default'/>
        <see cref = 'edge_cases.DAteTime'/>
        <see cref = 'edge_cases.FIle'/>
        <see cref = 'edge_cases.FIle.Links'/>
        <see cref = 'edge_cases.FIle.Matrix_Value'/>
        <see cref = 'edge_cases.Labels_Value'/>
        <see cref = 'edge_cases.NoArg'/>
        <see cref = 'edge_cases.SErver'/>
        <see cref = 'edge_cases.SEt'/>
        <see cref = 'edge_cases.Shape'/>
        <see cref = 'edge_cases.Square'/>
        <see cref = 'edge_cases.client2'/>
        <see cref = 'edge_cases.file2'/>
        <see cref = 'edge_cases.get_search_path_searchReq'/>
        <see cref = 'edge_cases.get_search_path_search_200'/>
        <see cref = 'edge_cases.get_search_path_search_200.Value_Item'/>
        <see cref = 'edge_cases.searchReq'/>
        <see cref = 'edge_cases.search_200'/>
    */
    [Title(@"Edge cases")]
    [Version(@"1")]
    [Description(@"A ""quoted"" description with <tags> & ampersands.")]
    public interface edge_cases {
        // 64-bit integers are `long` / `ulong` here, as `format: int64` says. A JSON number goes through a
        // double in JavaScript, so values above 2^53 never arrived there intact: if TypeScript hosts
        // matter and the values stay below that, `longJS` / `ulongJS` are the cheaper types.
        //
        // The document states ranges, never distributions. Where the values of an integer cluster - a
        // counter near its floor, a budget near its ceiling, a delta around zero - [A], [V] or [X] on
        // that field is the most valuable edit after conversion.

        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        public class FIle {
            string? File;
            string? name;
            CLient? Client;
            DAteTime? when;
            Uuid[,,]? ids;

            [Key: D(+20)]
            Set<string>? tags;
            Map<string, FIle.Matrix_Value>? matrix;
            FIle.Op? op;
            FIle.Level? level;

            [MinMax(0.0, 100.0)]
            double? ratio;

            [MinMax(1, 9)]
            int? count;

            /// <summary>constant: the spec allows only 8000</summary>
            int? Fixed;
            FIle.STatus? status;
            string? Status;
            FIle.Reason? reason;
            bool? marker; // typed with a pack that carries no value: being there is all it says
            Binary[,,]? anything; // any JSON in the spec: carried as raw bytes
            Binary[,,]? free; // any JSON in the spec: carried as raw bytes
            Anything? meta;

            /// <summary>wrapped ref</summary>
            CLient? owner;
            FIle.Links? links;
            string? Class;
            string? ref_like;

            public enum Op {
                unnamed, // =
                unnamed2, // !=
                unnamed3, // <
                unnamed4, // <=
                unnamed5, // >
                unnamed6, // >=
                like,
                LIKE2, // LIKE
            }

            public enum Level {
                x0 = 0,
                x1 = 1,
                x2 = 2,
            }

            public enum STatus {
                on,
                off,
            }

            public enum Reason {
                duplicate,
                won_t_fix, // won't fix
            }

            /// <summary>
            /// A value of `matrix`. AdHoc nests collections no deeper than a list of lists or a map of lists, so this level
            /// travels as a pack of its own.
            /// </summary>
            public class Matrix_Value {
                Map<string, double[,,]> value;
            }

            public class Links {
                string? SElf;
            }
        }

        public class CLient {
            long? id;
        }

        public class client2 {
            bool? legacy;
        }

        public class SErver {
            string? host;
        }

        public class DAteTime {
            long? epoch;
        }

        public class DUration {
            long TYPEDEF;
        }

        public class SEt {
            string[,,]? items;
        }

        public class file2 {
            int? size;
        }

        public class Anything {
            Binary[,,] TYPEDEF; // any JSON in the spec: carried as raw bytes
        }

        public class Marker { }

        public class Labels {
            Map<string, Labels_Value> TYPEDEF;
        }

        [DiscriminatorProperty(@"kind")]
        public class Shape {
            Circle? OneOf_Circle;
            Square? OneOf_Square;
            string? OneOf_OneOf0;
        }

        [DiscriminatorValue(@"circle")]
        public class Circle {
            string? kind;
            double? radius;
        }

        [DiscriminatorValue(@"square")]
        public class Square {
            string? kind;
            double? side;
        }

        /// <summary>
        /// A value of `TYPEDEF`. AdHoc nests collections no deeper than a list of lists or a map of lists, so this level
        /// travels as a pack of its own.
        /// </summary>
        public class Labels_Value {
            Map<string, string> value;
        }

        public class constants {
            public const string One = @"only";
        }

        [Validate(Regex = @"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$", MaxLength = 36)]
        public class Uuid {
            ulong hi;
            ulong lo;
        }

        public class searchReq {
            string? path; // in: query
            string? q; // in: query
        }

        /// <summary>ok</summary>
        public class search_200 {
            int? total;
        }

        /// <summary>HTTP response header `X-Rate-Limit`, parsed before the payload.</summary>
        public class X_Rate_Limit_int : HeaderFor<search_200> {
            int X_Rate_Limit;
        }

        /// <summary>HTTP response header `X-Rate-Limit`, parsed before the payload.</summary>
        public class X_Rate_Limit_long : HeaderFor<get_search_path_search_200> {
            long X_RAte_Limit;
        }

        public class Code_default { }

        public class get_search_path_searchReq {
            string path; // in: path
            string? Path; // in: query
        }

        /// <summary>ok</summary>
        public class get_search_path_search_200 {
            get_search_path_search_200.Value_Item[,,] value;

            /// <summary>
            /// An item of `value`. AdHoc nests collections no deeper than a list of lists or a map of lists, so this level
            /// travels as a pack of its own.
            /// </summary>
            public class Value_Item {
                string[,,][,,] value;
            }
        }

        public class Code_204 { }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            [HttpMethod(@"GET")]
            (L____________,
                /// <summary>ok</summary>
                FIle) root(NoArg _);

            public interface search {
                /// <summary>
                /// HTTP header on 200: X-Request-Id (String)
                /// operationId: search
                /// </summary>
                [HttpMethod(@"GET")]
                (L____________,
                    /// <summary>ok</summary>
                    search_200,
                    /// <summary>any error</summary>
                    Code_default) Search(searchReq req);

                // /search/{path}
                public interface path {
                    // /search/{path}/search
                    public interface SEarch {
                        [HttpMethod(@"GET")]
                        (L____________,
                            /// <summary>ok</summary>
                            get_search_path_search_200) get(get_search_path_searchReq req);
                    }
                }
            }

            // /Search
            public interface Search2 {
                [HttpMethod(@"DELETE")]
                (L____________,
                    /// <summary>gone</summary>
                    Code_204) Search(NoArg _);
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class DiscriminatorPropertyAttribute : Attribute { public DiscriminatorPropertyAttribute(string Property = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class DiscriminatorValueAttribute : Attribute { public DiscriminatorValueAttribute(string Value = "") { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        [AttributeUsage(AttributeTargets.All)] public class ValidateAttribute : Attribute { public string Regex { get; set; } = ""; public long MinLength { get; set; } = -1; public long MaxLength { get; set; } = -1; }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }

        public class DescriptionAttribute : Attribute { public DescriptionAttribute(string Description = "") { } }
    }
}
