// Generated by OpenAPI2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: oas32.yaml - OpenAPI 3.2, version 1 (OpenAPI 3.2)
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.openapi { // replace with your company namespace
    /**
        Packs Inventory. One line per transmittable pack, pre-tagged with the OpenAPI tags
        of the operations using it - route packs in branches by these tags (KeepDoc). Add
        your own tags/emojis after the `/>`. On its first run AdHocAgent carries the tags
        into its numbers tables, numbers the packs and gives a wire id to each pack that
        becomes directly transmittable.

        <see cref = 'oas32.Animal'/> animals
        <see cref = 'oas32.Cat'/>
        <see cref = 'oas32.Code_204'/>
        <see cref = 'oas32.Dog'/>
        <see cref = 'oas32.Filter'/> animals
        <see cref = 'oas32.NoArg'/>
    */
    [Title(@"OpenAPI 3.2")]
    [Version(@"1")]
    [TagDefinition(@"animals", @"", @"Animals", @"", @"nav")]
    [TagDefinition(@"dogs", @"", @"", @"animals", @"")]
    public interface oas32 {
        // Caps for collections that carry no explicit [D(...)] attribute. JSON APIs rarely declare bounds,
        // so these permissive defaults replace AdHoc's own limit of 255 items/chars. Put [D(+N)] on a
        // field whose real bound is known and tighten the rest.
        enum _DefaultMaxLengthOf { Arrays = 65_535, Maps = 65_535, Sets = 65_535, Strings = 65_535, }

        /// <summary>
        /// Synthetic pack representing an empty request or response.
        /// Used when an operation has no parameters or body.
        /// </summary>
        public class NoArg { }

        // ═════════════════════════ packs ═════════════════════════

        [OAuth2AuthDeviceAuthorization(@"https://example.com/device", @"https://example.com/token", @"")]
        [Obsolete(@"Deprecated")]
        public class device {
            public enum deviceScope {
                /// <summary>Read</summary>
                read,
                /// <summary>Write</summary>
                write,
            }
        }

        public class Filter {
            string? kind;

            /// <summary>the properties whose names match ^x-</summary>
            Map<string, string> patternProperties;
        }

        [DiscriminatorProperty(@"kind")]
        public class Animal {
            string kind;
            string? name;
        }

        [DiscriminatorValue(@"dog")]
        public class Dog : Animal {
            bool? barks;
        }

        [DiscriminatorValue(@"cat")]
        public class Cat : Animal {
            [MinMax(0, 9)]
            byte? lives;
        }

        public class Code_204 { }

        // ═════════════════════════ topology ═════════════════════════

        /// <summary>
        /// The API server. Server Definition: https://swagger.io/specification/#server-object
        /// https://api.example.com
        ///     Production
        /// </summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        [Server(@"https://api.example.com", @"Production", @"prod")]
        struct Server : Host { }

        /// <summary>The caller of the API.</summary>
        ///<see cref = 'InTS'/>   implementation in TypeScript
        ///<see cref = 'InCS'/>   implementation in C#
        ///<see cref = 'InJAVA'/> implementation in JAVA
        ///<see cref = 'InCPP'/>  implementation in C++
        ///<see cref = 'InRS'/>   implementation in RUST
        ///<see cref = 'InGO'/>   implementation in GO
        struct Client : Host { }

        interface ClientServerConnection : Connects<Client, Server> {
            public interface animals {
                /// <summary>tags: animals</summary>
                [HttpMethod(@"QUERY")]
                [Tag(@"animals", @"")]
                public interface searchAnimals : Actor {
                    int MaxActiveInstances => UNLIMITED;

                    [L____________<Return_searchAnimals, Filter>]
                    struct Call_searchAnimals { }

                    [____________r<Animal>]
                    [____________R<End, NoArg>]
                    struct Return_searchAnimals { }
                }

                [HttpMethod(@"PURGE")]
                (L____________,
                    /// <summary>Purged</summary>
                    Code_204) purgeAnimals(NoArg _);
            }
        }

        // ═════════════════════════ OpenAPI metadata attributes ═════════════════════════

        // Not read by AdHoc: they keep what the specification says and reach the generated code as constants.

        public class OAuth2AuthDeviceAuthorizationAttribute : Attribute { public OAuth2AuthDeviceAuthorizationAttribute(string DeviceAuthorizationUrl = "", string TokenUrl = "", string RefreshUrl = "") { } }

        public class ObsoleteAttribute : Attribute { public ObsoleteAttribute(string Message = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class ServerAttribute : Attribute { public ServerAttribute(string Url = "", string Description = "", string Name = "") { } }

        public class DiscriminatorPropertyAttribute : Attribute { public DiscriminatorPropertyAttribute(string Property = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class DiscriminatorValueAttribute : Attribute { public DiscriminatorValueAttribute(string Value = "") { } }

        public class HttpMethodAttribute : Attribute { public HttpMethodAttribute(string Method = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagAttribute : Attribute { public TagAttribute(string Name = "", string Description = "") { } }

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class TagDefinitionAttribute : Attribute { public TagDefinitionAttribute(string Name = "", string Description = "", string Summary = "", string Parent = "", string Kind = "") { } }

        public class TitleAttribute : Attribute { public TitleAttribute(string Title = "") { } }

        public class VersionAttribute : Attribute { public VersionAttribute(string Version = "") { } }
    }
}
